#!/usr/bin/env python3
"""showcase-finale generated files. Re-runnable, deterministic.
  assets/logo.png  256x96 end card: the site's chip mark over a 3x wordmark, BG1
  assets/sparks.png  obj sheet, 8x8 cells: glow frames, dim -> bright
  targets.lua  128 sprite landing spots spread over the logo's pixels
  song.json    the score: one 128-sixteenth pass at 96 BPM as pattern strings,
               finale.bin is the committed song source built from it (open
               it in the Studio's sequencer to edit the music)
"""
import json, pathlib, re
import numpy as np
from PIL import Image

here = pathlib.Path(__file__).resolve().parent

# ── logo: chip mark from the site's favicon (1-px rects) + the ppu-logo glyphs
svg = (here / "assets/chipmark.svg").read_text()   # the site favicon
chip = Image.new("RGBA", (43, 43), (0, 0, 0, 0)); px = chip.load()
for x, y, w, h, c in re.findall(r'<rect x="([\d.]+)" y="([\d.]+)" width="([\d.]+)" height="([\d.]+)" fill="(#[0-9a-f]+)"', svg):
    x, y, w, h = int(float(x)), int(float(y)), round(float(w)), round(float(h))
    for dx in range(w):
        for dy in range(h): px[x + dx, y + dy] = tuple(int(c[i:i + 2], 16) for i in (1, 3, 5)) + (255,)
chip = chip.crop(chip.getbbox())
G = {  # 7-wide glyphs on a 10-row grid, as in scripts/make_logo.py
"p": ["", "", "##.###.", "###..##", "##...##", "##...##", "###..##", "##.###.", "##.....", "##....."],
"u": ["", "", "##...##", "##...##", "##...##", "##...##", "##..###", ".###.##"],
"t": ["..##...", "..##...", "######.", "..##...", "..##...", "..##...", "..##.##", "...###."],
"o": ["", "", ".#####.", "##...##", "##...##", "##...##", "##...##", ".#####."],
"y": ["", "", "##...##", "##...##", "##...##", "##...##", "##..###", ".###.##", ".....##", ".#####."],
"s": ["", "", ".######", "##.....", ".####..", "...###.", ".....##", "######."],
".": ["", "", "", "", "", "", "..##...", "..##..."],
}
S, PITCH, WHITE, DOT = 3, 24, (244, 240, 255, 255), (184, 140, 255, 255)
logo = Image.new("RGBA", (256, 96), (0, 0, 0, 0)); lp = logo.load()
logo.paste(chip, ((256 - chip.width) // 2, 0), chip)
x0 = (256 - (7 * PITCH + 7 * S)) // 2
for i, ch in enumerate("ppu.toys"):
    for r, row in enumerate(G[ch]):
        for c, bit in enumerate(row):
            if bit == "#":
                for dy in range(S):
                    for dx in range(S): lp[x0 + i * PITCH + c * S + dx, 56 + r * S + dy] = DOT if ch == "." else WHITE
logo.save(here / "assets/logo.png")

# ── sparks: 8 cells, each a radial glow centred at (3.5, 3.5) ─────────────
RAMP = [(90, 40, 60), (170, 70, 50), (240, 130, 60), (255, 200, 110), (255, 245, 220)]
sheet = np.zeros((8, 64, 4), np.uint8)
for cell, (radius, peak) in enumerate([(0.6, 1), (0.8, 2), (1.2, 3), (1.6, 3), (2.0, 4), (2.6, 4), (3.2, 4), (3.6, 4)]):
    for y in range(8):
        for x in range(8):
            d = np.hypot(x - 3.5, y - 3.5)
            cross = min(abs(x - 3.5), abs(y - 3.5)) < 0.6          # star arms on the big frames
            reach = radius * (1.5 if cross and cell >= 5 else 1.0)
            if d <= reach:
                level = max(0, peak - int(d / reach * (peak + 1)))
                sheet[y, cell * 8 + x] = RAMP[level] + (255,)
Image.fromarray(sheet).save(here / "assets/sparks.png")

# ── landing targets: farthest-point sampling over the logo's opaque pixels
logo = np.array(Image.open(here / "assets/logo.png").convert("RGBA"))
ys, xs = np.nonzero(logo[:, :, 3])
pts = np.stack([xs, ys], 1).astype(float)
# Farthest-point spread, but no logo row may carry more than CAP sprites: the
# PPU drops the 33rd sprite on a line, and in-flight sprites need headroom.
CAP = 22
load = np.zeros(96 + 8, int)
def fits(y): return load[int(y) + 4 - 4:int(y) + 4 + 4].max() < CAP
def take(k):
    chosen.append(k); y = int(pts[k, 1]); load[y:y + 8] += 1
chosen = []
take(int(np.argmin(np.abs(pts[:, 0] - 128) + np.abs(pts[:, 1] - 20))))
dist = np.full(len(pts), np.inf)
for _ in range(127):
    dist = np.minimum(dist, np.hypot(*(pts - pts[chosen[-1]]).T))
    ok = np.array([fits(y) for y in pts[:, 1]])
    take(int(np.argmax(np.where(ok, dist, -1))))
tgt = pts[chosen]
order = np.argsort(np.arctan2(tgt[:, 1] - 48, tgt[:, 0] - 128))       # neighbours in the swarm land as neighbours
tgt = tgt[order]
rows = np.bincount(np.clip((tgt[:, 1][:, None] + np.arange(-4, 4)).astype(int).ravel(), 0, 95), minlength=96)
assert rows.max() <= 30, f"line budget: {rows.max()} sprites on one logo row"
(here / "targets.lua").write_text("-- generated by build_art.py: logo-space landing spots\nTARGETS = {\n" +
    "".join(f"  {{{int(x)}, {int(y)}}},\n" for x, y in tgt) + "}\n")

# ── score ─────────────────────────────────────────────────────────────────
# Bars 1-8, 16 sixteenths each. The logo lands on bar 7's downbeat (step 96 = 15 s).
CHORDS = [  # pad voicing (3 voices), arp tones (root..7th, then root up)
    (["A3", "C#4", "F#4"], ["D5", "F#5", "A5", "C#6", "D6"]),   # Dmaj7
    (["A3", "D4", "F#4"],  ["B4", "D5", "F#5", "A5", "B5"]),    # Bm7
    (["B3", "D4", "F#4"],  ["G4", "B4", "D5", "F#5", "G5"]),    # Gmaj7
    (["A3", "C#4", "E4"],  ["A4", "C#5", "E5", "G5", "A5"]),    # A7
    (["A3", "D4", "F#4"],  ["B4", "D5", "F#5", "A5", "B5"]),    # Bm7
    (["B3", "D4", "G4"],   ["G4", "B4", "D5", "F#5", "G5"]),    # Gmaj7 / A
    (["D4", "F#4", "A4"],  None),                                # Dadd9, held
    (None, None),
]
steps = 128
def track():
    return ["."] * steps
pad = [track() for _ in range(3)]; arp = track(); bell = track(); bass = track(); kick = track(); snare = track(); crash = track()
FIG = [0, 2, 1, 3, 2, 4, 3, 1, 0, 2, 1, 3, 2, 4, 3, 2]
for bar, (voicing, tones) in enumerate(CHORDS):
    s = bar * 16
    if voicing:
        for v in range(3): pad[v][s] = voicing[v]
    if bar == 5:                                    # second half of bar 6 lifts to A
        for v, n in enumerate(["A3", "C#4", "E4"]): pad[v][s + 8] = n
    if tones and bar < 2:                           # quarter-note bells: the first sparks
        for k in range(4): bell[s + k * 4] = tones[k]
    if tones and bar >= 2:
        for k in range(16): arp[s + k] = tones[FIG[k]]
        if bar == 5:                                # climb an octave into the landing
            up = ["A4", "C#5", "E5", "G5", "A5", "C#6", "E6", "G6"]
            for k in range(8): arp[s + 8 + k] = up[k]
for bar, root in [(2, "G2"), (3, "A2"), (4, "B2"), (5, "G2"), (6, "D2")]:
    bass[bar * 16] = root; bass[bar * 16 + 10] = root if bar < 6 else "."
bass[5 * 16 + 8] = "A2"
for s in range(64, 96, 8): kick[s] = "C4"
for s in range(88, 96): snare[s] = "C4"                # roll into the landing
kick[96] = "C4"; crash[96] = "C4"
for k, n in [(96, "D6"), (100, "A5"), (104, "E6"), (110, "F#5"), (116, "A5"), (122, "D6")]:
    bell[k] = n
for v in range(3): pad[v][124] = "^"
bass[124] = "^"
# voice, sound, vol, pan (-100..100); main.lua sets the bank presets' adsr/echo
TRACKS = [(0, "strings", 34, 0, pad[0]), (1, "strings", 30, -40, pad[1]), (2, "strings", 30, 40, pad[2]),
          (3, "pluck", 46, 25, arp), (4, "bell", 58, -20, bell), (5, "bass", 80, 0, bass),
          (6, "kick", 96, 0, kick), (7, "snare", 50, 0, snare), (7, "crash", 90, 0, crash)]
song = {"name": "finale", "tempo": 96, "steps": steps,
        "tracks": [{"voice": v, "sound": snd, "vol": vol, "pan": pan, "pattern": " ".join(tr)}
                   for v, snd, vol, pan, tr in TRACKS]}
(here / "song.json").write_text(json.dumps(song, indent=2) + "\n")   # finale.bin is built from this
print("targets rows max", rows.max())
