-- ppuglobals.lua · generated by the Studio panels. Edit values here or in the panels.
-- timeline: end=8 in=0 out=8 loop=true
-- loop markers: in=start out=loop_end
markers = {
  start = 0.000,
  loop_end = 8.000,
}

scanlines = {
}

function apply_pokes()
end
