use std::path::Path;

const SAMPLE_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/sample");
const SAMPLE_PPU_JSON: &str = include_str!("fixtures/sample.ppu.json");

fn run(args: &[&str]) -> std::process::Output {
    std::process::Command::new(env!("CARGO_BIN_EXE_ppu"))
        .args(args)
        .output()
        .unwrap()
}

fn success(args: &[&str]) -> String {
    let output = run(args);
    assert!(
        output.status.success(),
        "{args:?}: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    String::from_utf8(output.stdout).unwrap()
}

/// Read the RGBA pixel at (x=10, y) out of a rendered PNG (always RGBA8 —
/// see `crates/ppu-cli/src/author.rs`'s `write_header()`/`set_color`).
fn pixel_at(png_bytes: &[u8], y: u32) -> [u8; 4] {
    let decoder = png::Decoder::new(png_bytes);
    let mut reader = decoder.read_info().unwrap();
    let mut buf = vec![0; reader.output_buffer_size()];
    let info = reader.next_frame(&mut buf).unwrap();
    let idx = (y as usize * info.width as usize + 10) * 4;
    [buf[idx], buf[idx + 1], buf[idx + 2], buf[idx + 3]]
}

/// PPU-152 task 4: nothing in this crate's own tests had ever packed,
/// checked, or rendered a `ppuglobals.lua` that carries an actual poke —
/// `author.rs`'s `new_project_scaffolds_controls_lua_and_it_round_trips_through_check_and_render`
/// only proves the EMPTY scaffold's markers/loop_end resolve, and the SAMPLE
/// fixture's `pokes.lua` is a hand-written helper (not a poke at all). This
/// proves `check`/`render` actually apply a real controls document — a
/// frame-wide poke AND a banded override of the SAME property (cgram[0],
/// the backdrop color): the band's color must win only inside its own
/// scanline range — and that `pack`/`unpack` carry that document through
/// byte-for-byte (the re-rendered PNG is pixel-identical).
#[test]
fn pack_check_render_carries_a_real_controls_lua_poke() {
    let tmp = tempfile::tempdir().unwrap();
    let project = tmp.path().join("demo");
    std::fs::create_dir_all(&project).unwrap();
    std::fs::write(project.join("main.lua"), "function frame(t, f) end\n").unwrap();
    // Same shape crates/ppu-core/tests/controls.rs's fixtures use: a
    // frame-wide poke (applies to every row) and a band (100..223) that
    // overrides the SAME lvalue only on its own rows — HDMA to CGRAM is a
    // supported per-line effect (see crates/ppu-core/tests/cgram_hdma.rs).
    let controls = "-- ppuglobals.lua \u{b7} generated by the Studio panels. Edit values here or in the panels.\n\
-- timeline: end=30 in=0 out=30 loop=false\n\
-- loop markers: in= out=\n\
markers = {\n\n}\n\
\n\
scanlines = {\n  band = { first = 100, last = 223 },\n}\n\
\n\
function apply_pokes()\n\
  cgram[0] = 0x03e0\n\
  hdma(scanlines.band.first, scanlines.band.last, function(y)\n\
    cgram[0] = 0x001f\n\
  end)\n\
end\n";
    std::fs::write(project.join("ppuglobals.lua"), controls).unwrap();
    std::fs::write(
        project.join("ppu.json"),
        serde_json::json!({
            "title": "controls poke",
            "files": ["ppuglobals.lua", "main.lua"],
            "sources": [],
        })
        .to_string(),
    )
    .unwrap();

    let project = project.to_str().unwrap();
    success(&["check", project, "--duration", "0.1"]);
    let out1 = tmp.path().join("frames1");
    success(&["render", project, "--at", "0", "-o", out1.to_str().unwrap()]);
    let frame1 = std::fs::read(out1.join("frame-00000000.png")).unwrap();

    let above = pixel_at(&frame1, 10); // outside the band: the frame-wide poke alone
    let below = pixel_at(&frame1, 150); // inside the band (100..223): the band wins
    assert_ne!(
        above, below,
        "the band's poke must not leak outside its own range"
    );

    let packed = tmp.path().join("demo.ppu.json");
    success(&["pack", project, "-o", packed.to_str().unwrap()]);
    let copy = tmp.path().join("copy");
    success(&["unpack", packed.to_str().unwrap(), copy.to_str().unwrap()]);
    let out2 = tmp.path().join("frames2");
    success(&[
        "render",
        copy.to_str().unwrap(),
        "--at",
        "0",
        "-o",
        out2.to_str().unwrap(),
    ]);
    let frame2 = std::fs::read(out2.join("frame-00000000.png")).unwrap();
    assert_eq!(
        frame1, frame2,
        "pack/unpack must carry the controls document through byte-for-byte"
    );
}

#[test]
fn pack_sample_matches_committed_pin() {
    let packed = ppu_cli::pack(Path::new(SAMPLE_DIR)).unwrap();
    assert_eq!(packed.as_bytes(), SAMPLE_PPU_JSON.as_bytes());
}

#[test]
fn unpack_then_pack_round_trips_byte_for_byte() {
    let dir = tempfile::tempdir().unwrap();
    ppu_cli::unpack(SAMPLE_PPU_JSON, dir.path()).unwrap();

    assert!(dir.path().join("ppu.json").is_file());
    assert!(dir.path().join("main.lua").is_file());
    assert!(dir.path().join("pokes.lua").is_file());
    let payload = std::fs::read(dir.path().join(".ppu/sources/0.bin")).unwrap();
    assert_eq!(payload, vec![1, 2, 3, 4, 5]);

    let repacked = ppu_cli::pack(dir.path()).unwrap();
    assert_eq!(repacked.as_bytes(), SAMPLE_PPU_JSON.as_bytes());
}

#[test]
fn unpack_rejects_unknown_version() {
    let text = SAMPLE_PPU_JSON.replacen("\"ppu.toys/1\"", "\"ppu.toys/0\"", 1);
    let dir = tempfile::tempdir().unwrap();
    let err = ppu_cli::unpack(&text, dir.path()).unwrap_err();
    assert!(
        err.to_string().contains("version"),
        "unexpected error: {err}"
    );
}

#[test]
fn unpack_rejects_unsafe_file_names_before_writing_anything() {
    let mut value: serde_json::Value = serde_json::from_str(SAMPLE_PPU_JSON).unwrap();
    value["files"]
        .as_array_mut()
        .unwrap()
        .push(serde_json::json!({ "name": "../evil.lua", "source": "-- evil" }));
    let text = serde_json::to_string(&value).unwrap();

    let dir = tempfile::tempdir().unwrap();
    let err = ppu_cli::unpack(&text, dir.path()).unwrap_err();
    assert!(
        err.to_string().contains("unsafe"),
        "unexpected error: {err}"
    );

    assert!(!dir.path().join("ppu.json").exists());
    assert!(!dir.path().join("evil.lua").exists());
    assert_eq!(std::fs::read_dir(dir.path()).unwrap().count(), 0);
}

#[test]
fn unpack_rejects_missing_version() {
    let mut value: serde_json::Value = serde_json::from_str(SAMPLE_PPU_JSON).unwrap();
    value.as_object_mut().unwrap().remove("version");
    let text = serde_json::to_string(&value).unwrap();

    let dir = tempfile::tempdir().unwrap();
    let err = ppu_cli::unpack(&text, dir.path()).unwrap_err();
    assert!(
        format!("{err:#}").contains("not a ppu.toys file"),
        "unexpected error: {err:#}"
    );
}

#[test]
fn unpack_rejects_bad_payload_before_writing_anything() {
    let mut value: serde_json::Value = serde_json::from_str(SAMPLE_PPU_JSON).unwrap();
    value["sources"][0]["payload"] = serde_json::json!("!!!");
    let text = serde_json::to_string(&value).unwrap();

    let dir = tempfile::tempdir().unwrap();
    let err = ppu_cli::unpack(&text, dir.path()).unwrap_err();
    let msg = format!("{err:#}");
    assert!(msg.contains("sky"), "unexpected error: {msg}");
    assert!(msg.contains("payload"), "unexpected error: {msg}");

    assert!(!dir.path().join("main.lua").exists());
    assert!(!dir.path().join("ppu.json").exists());
}

fn copy_dir_all(src: &Path, dst: &Path) {
    std::fs::create_dir_all(dst).unwrap();
    for entry in std::fs::read_dir(src).unwrap() {
        let entry = entry.unwrap();
        let dst_path = dst.join(entry.file_name());
        if entry.file_type().unwrap().is_dir() {
            copy_dir_all(&entry.path(), &dst_path);
        } else {
            std::fs::copy(entry.path(), &dst_path).unwrap();
        }
    }
}

#[test]
fn pack_rejects_manifest_without_main_lua() {
    let dir = tempfile::tempdir().unwrap();
    copy_dir_all(Path::new(SAMPLE_DIR), dir.path());

    let mut manifest: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(dir.path().join("ppu.json")).unwrap())
            .unwrap();
    manifest["files"] = serde_json::json!(["pokes.lua"]);
    std::fs::write(
        dir.path().join("ppu.json"),
        serde_json::to_string_pretty(&manifest).unwrap(),
    )
    .unwrap();

    let err = ppu_cli::pack(dir.path()).unwrap_err();
    let msg = err.to_string();
    assert!(msg.contains("main.lua"), "unexpected error: {msg}");
    assert!(
        msg.contains(&dir.path().join("ppu.json").display().to_string()),
        "unexpected error: {msg}"
    );
}

#[test]
fn pack_rejects_unsafe_source_payload_path() {
    let dir = tempfile::tempdir().unwrap();
    std::fs::write(dir.path().join("main.lua"), "function frame(t, f) end\n").unwrap();
    std::fs::write(
        dir.path().join("ppu.json"),
        serde_json::json!({
            "title": "t",
            "description": "",
            "files": ["main.lua"],
            "sources": [{
                "name": "s",
                "kind": "bg",
                "options": {},
                "meta": {},
                "payload": "../x.bin",
            }],
        })
        .to_string(),
    )
    .unwrap();

    let err = ppu_cli::pack(dir.path()).unwrap_err();
    assert!(
        err.to_string().contains("unsafe"),
        "unexpected error: {err}"
    );
}

// A sample source travels through unpack -> pack untouched: pack/unpack copy
// `kind`, `meta` and the payload bytes verbatim, so a kind they never heard of
// (BRR audio, not an image) needs no CLI change.
#[test]
fn sample_source_round_trips_through_unpack_and_pack() {
    use base64::Engine;
    let pcm: Vec<i16> = (0..640)
        .map(|i| ((i as f64 * std::f64::consts::TAU / 32.0).sin() * 20000.0).round() as i16)
        .collect();
    let opts = ppu_core::ConvertSampleOptions {
        loop_start: Some(96),
    };
    let (payload, meta) = ppu_core::convert_sample(&pcm, &opts).unwrap();
    let bytes = payload.encode();

    let mut value: serde_json::Value = serde_json::from_str(SAMPLE_PPU_JSON).unwrap();
    value["sources"]
        .as_array_mut()
        .unwrap()
        .push(serde_json::json!({
            "name": "kick",
            "kind": "sample",
            "builtinId": null,
            "options": { "loop_start": 96 },
            "meta": serde_json::to_value(&meta).unwrap(),
            "payload": base64::engine::general_purpose::STANDARD.encode(&bytes),
        }));
    let text = serde_json::to_string(&value).unwrap();

    let dir = tempfile::tempdir().unwrap();
    ppu_cli::unpack(&text, dir.path()).unwrap();
    assert_eq!(
        std::fs::read(dir.path().join(".ppu/sources/1.bin")).unwrap(),
        bytes
    );

    let repacked: serde_json::Value =
        serde_json::from_str(&ppu_cli::pack(dir.path()).unwrap()).unwrap();
    assert_eq!(repacked, value);
}
