import type { Story, StoryDefault } from "@ladle/react";
import { CodeEditor } from "./CodeEditor";
import { luaSource } from "../../fixtures";

// CodeEditor wraps a CodeMirror view — it reads no wasm core, transport, or
// store; its props (docKey/doc/generated/onChange/errors) fully drive it, so a
// static-source story with a no-op onChange and no run loop renders it honestly
// wasm-free (this is the "renders meaningfully wasm-free" case the ticket calls
// out). Source pushing / error routing live in EditorPane and are not exercised
// here. Wrapped in a sized box because the editor fills its parent's height.
export default {
  title: "Studio/Editor/CodeEditor",
} satisfies StoryDefault;

function Frame({ children }: { children: React.ReactNode }) {
  return (
    <div style={{ height: 340, width: 560, border: "1px solid var(--line2)", overflow: "hidden" }}>
      {children}
    </div>
  );
}

const noop = () => {};

export const Default: Story = () => (
  <Frame>
    <CodeEditor docKey="doc0" doc={luaSource} onChange={noop} errors={[]} />
  </Frame>
);

// A routed compile error on line 1 → inline diagnostic + lint-gutter marker.
export const WithError: Story = () => (
  <Frame>
    <CodeEditor
      docKey="doc1"
      doc={"local x =\nprint(x)\n"}
      onChange={noop}
      errors={[{ message: "unexpected symbol near <eof>", line: 1 }]}
    />
  </Frame>
);

// Machine-generated, read-only doc (pokes.lua) — its buffer is rebuilt from the
// `doc` prop rather than treated as the source of truth.
export const Generated: Story = () => (
  <Frame>
    <CodeEditor
      docKey="doc2"
      doc={"-- generated by the poke inspector\npoke(0x2100, 0x0f)\n"}
      generated
      onChange={noop}
      errors={[]}
    />
  </Frame>
);
