import type { SourceFile } from "../../ppu/core";
import { useSyncExternalStore } from "react";

export const TIMELINE_FILE = "timeline.lua";
export interface TimelineMarker {
  name: string;
  time: number;
}

export interface TimelineSettings {
  end: number;
  loopIn: number;
  loopOut: number;
  looping: boolean;
}

export const DEFAULT_TIMELINE: TimelineSettings = {
  end: 30,
  loopIn: 0,
  loopOut: 30,
  looping: false,
};
let settings: TimelineSettings = DEFAULT_TIMELINE;
const listeners = new Set<() => void>();
export const timelineSettings = {
  get: () => settings,
  subscribe: (listener: () => void) => {
    listeners.add(listener);
    return () => void listeners.delete(listener);
  },
  set(next: Partial<TimelineSettings>) {
    settings = { ...settings, ...next };
    for (const listener of listeners) listener();
  },
};

export function useTimelineSettings(): TimelineSettings {
  return useSyncExternalStore(timelineSettings.subscribe, timelineSettings.get);
}

export function timelineMarkers(files: readonly SourceFile[]): TimelineMarker[] {
  const source = files.find((file) => file.name === TIMELINE_FILE)?.source ?? "";
  return [...source.matchAll(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(\d+(?:\.\d+)?)\s*,?\s*$/gm)]
    .map((match) => ({ name: match[1], time: Number(match[2]) }))
    .sort((a, b) => a.time - b.time || a.name.localeCompare(b.name));
}

export function timelineConfig(files: readonly SourceFile[]): TimelineSettings {
  const source = files.find((file) => file.name === TIMELINE_FILE)?.source ?? "";
  const match = source.match(
    /^-- timeline: end=(\d+(?:\.\d+)?) in=(\d+(?:\.\d+)?) out=(\d+(?:\.\d+)?) loop=(true|false)$/m,
  );
  if (!match) return DEFAULT_TIMELINE;
  return {
    end: Math.max(1, Number(match[1])),
    loopIn: Number(match[2]),
    loopOut: Number(match[3]),
    looping: match[4] === "true",
  };
}

export function markerSource(
  markers: readonly TimelineMarker[],
  config: TimelineSettings = settings,
): string {
  const rows = [...markers]
    .sort((a, b) => a.time - b.time || a.name.localeCompare(b.name))
    .map(({ name, time }) => `  ${name} = ${time.toFixed(3)},`);
  return `-- Generated by the Output timeline. Values are seconds.\n-- timeline: end=${config.end} in=${config.loopIn} out=${config.loopOut} loop=${config.looping}\nmarkers = {\n${rows.join("\n")}\n}\n`;
}
