/** Poke model: pokes are canonical DSL assignments living in a fully
 *  machine-generated `pokes.lua`. The FILE is the source of truth — the UI
 *  regenerates the whole apply_pokes() block on every poke and parses it back
 *  on load. The engine knows nothing about pokes. */

export const POKES_FILE = "pokes.lua";

export interface Poke {
  /** DSL lvalue, e.g. "TM" or "cgram[0x41]" — the poke's identity key. */
  lvalue: string;
  /** RHS expression, e.g. "0x13" or "40". */
  expr: string;
  /** Optional trailing annotation rendered as `-- note`. */
  note?: string;
}

const HEADER = `-- pokes.lua · generated by the inspector — read-only.
-- Poke register/CGRAM values in the inspector to fill this in. To save a
-- configuration, copy apply_pokes() into your own file under a new name.
-- Hand-edits here are overwritten by the next poke.`;

export function pokesToLua(pokes: readonly Poke[]): string {
  const body = [...pokes]
    // codepoint compare, NOT localeCompare — generated output must be
    // byte-identical across machines (shared sketches, goldens)
    .sort((a, b) => (a.lvalue < b.lvalue ? -1 : a.lvalue > b.lvalue ? 1 : 0))
    .map((p) => `  ${p.lvalue} = ${p.expr}${p.note ? ` -- ${p.note}` : ""}`)
    .join("\n");
  return `${HEADER}\nfunction apply_pokes()\n${body}${body ? "\n" : ""}end\n`;
}

export const EMPTY_POKES = pokesToLua([]);

/** One generated poke line: two-space indent, `lvalue = expr`, optional `-- note`.
 *  lvalue must be a single whitespace-free token so hand-written/tampered
 *  lines (which tend to contain spaces before any `=`) are never mistaken
 *  for machine-generated pokes. */
const LINE = /^ {2}(\S+) = (.+?)(?: -- (.*))?$/;

export function parsePokes(src: string): Poke[] {
  const block = src.match(/function apply_pokes\(\)\n([\s\S]*?)^end/m);
  if (!block) return [];
  return block[1].split("\n").flatMap((line) => {
    const g = LINE.exec(line);
    if (!g) return [];
    return [{ lvalue: g[1], expr: g[2], ...(g[3] !== undefined ? { note: g[3] } : {}) }];
  });
}

export function upsertPoke(pokes: readonly Poke[], next: Poke): Poke[] {
  const rest = pokes.filter((p) => p.lvalue !== next.lvalue);
  return [...rest, next];
}
