/** Poke model: pokes are canonical DSL assignments living in a fully
 *  machine-generated `pokes.lua`. The FILE is the source of truth — the UI
 *  regenerates the whole apply_pokes() block on every poke and parses it back
 *  on load. The engine knows nothing about pokes. */

import { isScanlinePoke, pkHelper, pokeRange } from "./scanlinePokes";

export const POKES_FILE = "pokes.lua";

export interface Poke {
  /** DSL lvalue, e.g. "TM" or "cgram[0x41]" — the poke's identity key. */
  lvalue: string;
  /** RHS expression, e.g. "0x13" or "40". */
  expr: string;
  /** Optional trailing annotation rendered as `-- note`. */
  note?: string;
  /** SCANLINE pokes only: the inclusive line range its generated `hdma()` hook
   *  covers. Absent = the whole frame (`DEFAULT_RANGE`). Pokes sharing a range
   *  share one hook; different ranges become separate hooks, which is why a
   *  poke can be scoped to a band and leave the rest of the frame to the
   *  script. Meaningless on a frame-wide poke, which has no hook. */
  range?: readonly [number, number];
}

const HEADER = `-- pokes.lua · generated by the inspector — read-only.
-- Poke register/CGRAM values in the inspector to fill this in. To save a
-- configuration, copy apply_pokes() into your own file under a new name.
-- Hand-edits here are overwritten by the next poke.`;

/** Emitted ONLY when a scanline poke exists, so a sketch with none stays
 *  byte-identical to what it always generated (every bundled demo ships an
 *  empty pokes.lua — that output must not churn).
 *
 *  `pki` rounds because the DSL silently ignores a fractional write to an
 *  integer register; `pkf` is for the genuinely fractional fields (m7.a-d). */
const SCANLINE_PREAMBLE = `-- Per-scanline pokes: keyframes {{y,value},…} interpolated down the frame,
-- holding the end values outside the keyframed range.
local function pk(kf, y)
  local n = #kf
  if y <= kf[1][1] then return kf[1][2] end
  for i = 2, n do
    local a, b = kf[i - 1], kf[i]
    if y <= b[1] then
      local d = b[1] - a[1]
      if d <= 0 then return b[2] end
      return a[2] + (b[2] - a[2]) * (y - a[1]) / d
    end
  end
  return kf[n][2]
end
local function pki(kf, y) return floor(pk(kf, y) + 0.5) end
local function pkf(kf, y) return pk(kf, y) end
`;

const note = (p: Poke) => (p.note ? ` -- ${p.note}` : "");

// codepoint compare, NOT localeCompare — generated output must be
// byte-identical across machines (shared sketches, goldens)
const byLvalue = (a: Poke, b: Poke) => (a.lvalue < b.lvalue ? -1 : a.lvalue > b.lvalue ? 1 : 0);

/** Regenerate the whole file. Frame-wide pokes are plain assignments; scanline
 *  pokes are grouped by range, ONE `hdma()` hook per distinct range, after the
 *  frame-wide lines. Hooks compose (see `crates/ppu-core/tests/hook_composition.rs`),
 *  so several scoped hooks each doing their own thing is the normal case, not a
 *  workaround.
 *
 *  These hooks register while `apply_pokes()` runs — before any hook the script
 *  registers later — so a script `hdma()` still wins, matching the frame-wide
 *  convention. Within its own range a scanline poke does beat a plain script
 *  assignment, because a hook always beats the frame defaults (real HDMA
 *  behaves the same way); scoping the range is how you leave the rest of the
 *  frame to the script. */
export function pokesToLua(pokes: readonly Poke[]): string {
  const sorted = [...pokes].sort(byLvalue);
  const flat = sorted.filter((p) => !isScanlinePoke(p));
  const scan = sorted.filter(isScanlinePoke);
  const lines = flat.map((p) => `  ${p.lvalue} = ${p.expr}${note(p)}`);

  // Group by range, then emit groups in range order — deterministic output for
  // any input order, which the byte-stability contract requires.
  const groups = new Map<string, Poke[]>();
  for (const p of scan) {
    const [y0, y1] = pokeRange(p);
    const key = `${y0},${y1}`;
    (groups.get(key) ?? groups.set(key, []).get(key)!).push(p);
  }
  const ordered = [...groups].sort(([a], [b]) => {
    const [a0, a1] = a.split(",").map(Number);
    const [b0, b1] = b.split(",").map(Number);
    return a0 - b0 || a1 - b1;
  });
  for (const [key, ps] of ordered) {
    const [y0, y1] = key.split(",");
    lines.push(`  hdma(${y0}, ${y1}, function(y)`);
    for (const p of ps) {
      lines.push(`    ${p.lvalue} = ${pkHelper(p.lvalue)}(${p.expr}, y)${note(p)}`);
    }
    lines.push(`  end)`);
  }

  const body = lines.join("\n");
  const preamble = scan.length > 0 ? SCANLINE_PREAMBLE : "";
  return `${HEADER}\n${preamble}function apply_pokes()\n${body}${body ? "\n" : ""}end\n`;
}

export const EMPTY_POKES = pokesToLua([]);

/** One generated poke line: two-space indent, `lvalue = expr`, optional `-- note`.
 *  lvalue must be a single whitespace-free token so hand-written/tampered
 *  lines (which tend to contain spaces before any `=`) are never mistaken
 *  for machine-generated pokes. The hook's own `  hdma(…` / `  end)` lines
 *  carry no ` = ` and so can never match this. */
const LINE = /^ {2}(\S+) = (.+?)(?: -- (.*))?$/;

/** One scanline poke line: four-space indent (inside the generated hook), the
 *  keyframe table unwrapped from its `pki(…, y)` / `pkf(…, y)` call. Parsing
 *  yields the SAME `{lvalue, expr}` shape as a frame-wide poke — the expr is
 *  the keyframe table — so everything downstream is dialect-agnostic. */
const SCAN_LINE = /^ {4}(\S+) = pk[if]\((\{.*\}), y\)(?: -- (.*))?$/;

/** The generated hook header — its range is the enclosing scanline pokes'. */
const HOOK_OPEN = /^ {2}hdma\((\d+), (\d+), function\(y\)$/;
const HOOK_CLOSE = /^ {2}end\)$/;

export function parsePokes(src: string): Poke[] {
  // `^end` is column-0, and every line inside the hook is indented, so the
  // hook's `  end)` cannot terminate the block early.
  const block = src.match(/function apply_pokes\(\)\n([\s\S]*?)^end/m);
  if (!block) return [];
  const out: Poke[] = [];
  // Parsing is stateful only across a hook's own lines: the range lives on the
  // `hdma(...)` header, which is where it belongs in readable Lua, rather than
  // being smuggled into every keyframe expr.
  let range: readonly [number, number] | null = null;
  for (const line of block[1].split("\n")) {
    const open = HOOK_OPEN.exec(line);
    if (open) {
      range = [Number(open[1]), Number(open[2])];
      continue;
    }
    if (HOOK_CLOSE.test(line)) {
      range = null;
      continue;
    }
    const flat = LINE.exec(line);
    if (flat) {
      out.push({
        lvalue: flat[1],
        expr: flat[2],
        ...(flat[3] !== undefined ? { note: flat[3] } : {}),
      });
      continue;
    }
    const scan = SCAN_LINE.exec(line);
    if (scan) {
      out.push({
        lvalue: scan[1],
        expr: scan[2],
        ...(scan[3] !== undefined ? { note: scan[3] } : {}),
        ...(range ? { range } : {}),
      });
    }
  }
  return out;
}

export function upsertPoke(pokes: readonly Poke[], next: Poke): Poke[] {
  const rest = pokes.filter((p) => p.lvalue !== next.lvalue);
  return [...rest, next];
}
