//! Automatic controls application (PPU-147): with a `ppuglobals.lua` in the
//! file list, its `apply_pokes` applies every frame as a final visual
//! override pass — registers on every line, OAM/CGRAM/VRAM in `memory()` —
//! program state is untouched by it (an override never bakes into the
//! program's own baseline or compounds an accumulator), a controls-only
//! `set_sources` never recompiles, and a broken controls edit is refused
//! while the last valid controls keep applying. Driven entirely through
//! `LuaEngine`'s public API (`set_sources`/`frame`/`memory`/`audio`,
//! `LineTable.rows[y]`) — never reaching into the VM.
mod common;
use ppu_core::LuaEngine;

/// A hand-copied fixture of the document shape `web/src/studio/pokes/controls.ts`
/// (PPU-146) generates — NOT a cross-language contract test; the TS
/// generator can drift from this without either side failing here.
/// `markers`/`scanlines` stay present (empty) even when `body` doesn't use
/// them.
fn controls(body: &str) -> String {
    controls_with_scanlines("", body)
}

/// Same as `controls`, but with `scanlines_body` spliced into the
/// `scanlines = {...}` table instead of leaving it empty — for tests whose
/// `apply_pokes` references `scanlines.<name>.first`/`.last`.
fn controls_with_scanlines(scanlines_body: &str, body: &str) -> String {
    format!(
        "-- ppuglobals.lua · generated by the Studio panels. Edit values here or in the panels.\n\
         -- timeline: end=30 in=0 out=30 loop=false\n\
         -- loop markers: in= out=\n\
         markers = {{\n}}\n\
         \n\
         scanlines = {{\n{scanlines_body}}}\n\
         \n\
         function apply_pokes()\n\
         {body}\
         end\n"
    )
}

/// Same as `controls_with_scanlines`, but with the `pk`/`pki`/`pkf`
/// per-scanline-poke preamble spliced immediately before `apply_pokes` — the
/// shape the generated document takes when any keyframe curve is present.
/// Verbatim copy of the preamble text in `scanline_pokes.rs`'s `GENERATED`
/// (from `-- Per-scanline pokes:` through the `pkf` one-liner) — keep it
/// byte-identical to that.
fn controls_with_curve(scanlines_body: &str, body: &str) -> String {
    const PREAMBLE: &str = r#"-- Per-scanline pokes: keyframes {{y,value},…} interpolated down the frame,
-- holding the end values outside the keyframed range.
local function pke(t, easing)
  if easing == "smooth" then return t * t * (3 - 2 * t) end
  if easing == "ease-in" then return t * t end
  if easing == "ease-out" then return t * (2 - t) end
  if easing == "step" then return t < 1 and 0 or 1 end
  return t
end
local function pk(kf, y)
  local n = #kf
  if y <= kf[1][1] then return kf[1][2] end
  for i = 2, n do
    local a, b = kf[i - 1], kf[i]
    if y <= b[1] then
      local d = b[1] - a[1]
      if d <= 0 then return b[2] end
      return a[2] + (b[2] - a[2]) * pke((y - a[1]) / d, a[3])
    end
  end
  return kf[n][2]
end
local function pki(kf, y) return floor(pk(kf, y) + 0.5) end
local function pkf(kf, y) return pk(kf, y) end
"#;
    controls_with_scanlines(scanlines_body, body).replacen(
        "function apply_pokes()",
        &format!("{PREAMBLE}function apply_pokes()"),
        1,
    )
}

/// BRR/directory poke helpers, copied from `dsp_timers.rs` (see that file's
/// doc comment for the layout) — a sounding voice 0 for the controls-only
/// reload / invalid-controls / runtime-error tests, which must prove the DSP
/// keeps running underneath a controls-only push.
fn brr_pokes(base: u16, blocks: usize, last_header: u8) -> String {
    let mut s = String::new();
    for b in 0..blocks {
        let addr = base as usize + b * 9;
        let header = if b == blocks - 1 { last_header } else { 0xc0 };
        s += &format!("aram[{addr}] = {header}\n");
        for (i, byte) in [0x77u8, 0x77, 0x77, 0x77, 0x99, 0x99, 0x99, 0x99]
            .iter()
            .enumerate()
        {
            s += &format!("aram[{}] = {byte}\n", addr + 1 + i);
        }
    }
    s
}

fn dir_entry_pokes(index: u8, start: u16, loop_addr: u16) -> String {
    let addr = 0x0100 + index as usize * 4;
    format!(
        "aram[{a0}] = {b0}\naram[{a1}] = {b1}\naram[{a2}] = {b2}\naram[{a3}] = {b3}\n",
        a0 = addr,
        b0 = start & 0xff,
        a1 = addr + 1,
        b1 = (start >> 8) & 0xff,
        a2 = addr + 2,
        b2 = loop_addr & 0xff,
        a3 = addr + 3,
        b3 = (loop_addr >> 8) & 0xff,
    )
}

/// `main.lua` for the audio-continuity tests: `init()` pokes a 6-block
/// looping BRR sample (directory entry 0, ARAM 0x0200) and seeds `n = 0`;
/// a `timer(0, 64, ..)` counts `ticks`; `frame()` advances `n`, mirrors both
/// into `bg[2]`/`bg[3]` scroll so a test can read them back through the
/// LineTable, drives voice 0's registers every frame (matches
/// `dsp_timers.rs`'s known-good VOICE0_SETUP fields), and keys it on at f=0.
fn voice0_main() -> String {
    format!(
        "function init()\n\
           n = 0\n\
         {sample}{dir}\
         end\n\
         timer(0, 64, function() ticks = (ticks or 0) + 1 end)\n\
         function frame(t, f)\n\
           n = n + 1\n\
           bg[2].scroll.x = n\n\
           bg[3].scroll.x = ticks or 0\n\
           voice[0].sample = 0\n\
           voice[0].pitch = 0x1000\n\
           voice[0].vol.l = 127\n\
           voice[0].vol.r = 127\n\
           voice[0].adsr = {{a = 15, d = 0, s = 7, r = 0}}\n\
           dsp.mvol.l = 127\n\
           dsp.mvol.r = 127\n\
           if f == 0 then kon(0) end\n\
         end\n",
        sample = brr_pokes(0x0200, 6, 0xc3),
        dir = dir_entry_pokes(0, 0x0200, 0x0200),
    )
}

fn has_sound(audio: &[i16]) -> bool {
    audio.iter().any(|&s| s != 0)
}

/// (a) A frame-wide controls override beats the program's own per-frame
/// write; releasing it (pushing an empty `apply_pokes`) returns ownership to
/// the program on the very next frame — no `reset()` involved.
#[test]
fn frame_wide_override_beats_the_programs_own_write_and_release_returns_ownership() {
    let main = "function frame(t, f) brightness = 5 end";
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("main.lua", main),
        ("ppuglobals.lua", &controls("  brightness = 12\n")),
    ])
    .unwrap();
    let lt = e.frame(0.0, 0).unwrap();
    assert_eq!(lt.rows[0].brightness, 12);
    assert_eq!(lt.rows[223].brightness, 12);

    e.set_sources(&[("main.lua", main), ("ppuglobals.lua", &controls(""))])
        .unwrap();
    let lt = e.frame(0.0, 1).unwrap();
    assert_eq!(
        lt.rows[0].brightness, 5,
        "release should return ownership to the program"
    );
}

/// (b) Overriding an animated property and then releasing it must not bake
/// the override into the program's own baseline or compound its
/// accumulator: `obj[0].x` is both the program's OWN accumulator (it
/// increments itself) and something controls overrides — after release the
/// program's progression must be exactly what it would have been had
/// controls never run.
#[test]
fn releasing_an_override_never_bakes_in_or_compounds_the_accumulator() {
    let main = "function frame(t, f)\n\
                  x = (x or 0) + 1\n\
                  bg[1].scroll.x = x\n\
                  obj[0].x = obj[0].x + 1\n\
                end\n";
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("main.lua", main),
        (
            "ppuglobals.lua",
            &controls("  bg[1].scroll.x = 100\n  obj[0].x = 96\n"),
        ),
    ])
    .unwrap();

    for f in 0..5u32 {
        let lt = e.frame(0.0, f).unwrap();
        assert_eq!(
            lt.rows[0].bg[0].scroll_x, 100,
            "frame {f}: override should be visible"
        );
        assert_eq!(
            e.memory().oam[0].x,
            96,
            "frame {f}: override should be visible in memory"
        );
    }

    e.set_sources(&[("main.lua", main), ("ppuglobals.lua", &controls(""))])
        .unwrap();
    let lt = e.frame(0.0, 5).unwrap();
    assert_eq!(
        lt.rows[0].bg[0].scroll_x, 6,
        "the program's own x should be exactly 6 (5 prior frames + this one), not 106"
    );
    assert_eq!(
        e.memory().oam[0].x,
        6,
        "the program's own obj[0].x should be exactly 6, not 102"
    );
}

/// (c) A controls frame-wide override composes with the program's OWN
/// authored `hdma`: within the hook's range the hook's own value for a
/// property controls didn't touch survives; outside it, the property that
/// was never overridden by anything shows the frame-wide default.
#[test]
fn frame_wide_override_composes_with_the_programs_own_hdma() {
    let main = "function frame(t, f)\n\
                  brightness = 9\n\
                  hdma(100, 150, function(y)\n\
                    bg[1].scroll.x = 7\n\
                    brightness = 3\n\
                  end)\n\
                end\n";
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("main.lua", main),
        ("ppuglobals.lua", &controls("  bg[1].scroll.x = 24\n")),
    ])
    .unwrap();
    let lt = e.frame(0.0, 0).unwrap();

    for y in [10usize, 120, 200] {
        assert_eq!(
            lt.rows[y].bg[0].scroll_x, 24,
            "row {y}: controls always wins bg1 scroll x"
        );
    }
    assert_eq!(
        lt.rows[120].brightness, 3,
        "inside main's own hdma range, its own write survives"
    );
    assert_eq!(
        lt.rows[10].brightness, 9,
        "outside it, the frame-wide default (controls didn't touch it)"
    );
}

/// (d) Memory precedence: a controls override on one field of a poke surface
/// (VRAM word, CGRAM entry, one OAM property) overlays only what it touches,
/// leaving the program's other pokes on the same surfaces untouched;
/// releasing restores exactly the program's own memory state.
#[test]
fn memory_precedence_overlays_only_what_controls_touches() {
    let main = "function frame(t, f)\n\
                  vram[0x1000] = 0x1111\n\
                  vram[0x1001] = 0x3333\n\
                  cgram[1] = 0x0001\n\
                  obj[0].tile = 7\n\
                end\n";
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("main.lua", main),
        (
            "ppuglobals.lua",
            &controls("  vram[0x1000] = 0x2222\n  cgram[1] = 0x7fff\n  obj[0].x = 96\n"),
        ),
    ])
    .unwrap();
    e.frame(0.0, 0).unwrap();
    assert_eq!(e.memory().vram[0x1000], 0x2222);
    assert_eq!(
        e.memory().vram[0x1001],
        0x3333,
        "untouched by controls, main's write survives"
    );
    assert_eq!(e.memory().cgram[1], 0x7fff);
    assert_eq!(
        e.memory().oam[0].tile,
        7,
        "untouched by controls, main's write survives"
    );
    assert_eq!(e.memory().oam[0].x, 96);

    e.set_sources(&[("main.lua", main), ("ppuglobals.lua", &controls(""))])
        .unwrap();
    e.frame(0.0, 1).unwrap();
    assert_eq!(e.memory().vram[0x1000], 0x1111);
    assert_eq!(e.memory().cgram[1], 0x0001);
    assert_eq!(e.memory().oam[0].x, 0);
}

/// (e) A controls-only `set_sources` never recompiles: the VM, its running
/// voice, the timer phase, and the program's own accumulators all keep
/// going. Contrast: an actual `main.lua` change forces a real recompile
/// (init reruns), proving the fast path really is what preserved state above.
#[test]
fn controls_only_reload_keeps_the_vm_hot_full_recompile_does_not() {
    let main = voice0_main();
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("main.lua", &main),
        ("ppuglobals.lua", &controls("  brightness = 3\n")),
    ])
    .unwrap();

    let mut lt4 = None;
    for f in 0..5u32 {
        lt4 = Some(e.frame(0.0, f).unwrap());
    }
    let lt4 = lt4.unwrap();
    assert!(
        has_sound(e.audio()),
        "voice 0 should still be sounding after 5 frames"
    );
    let ticks4 = lt4.rows[0].bg[2].scroll_x;

    e.set_sources(&[
        ("main.lua", &main),
        ("ppuglobals.lua", &controls("  brightness = 4\n")),
    ])
    .unwrap();
    let lt5 = e.frame(0.0, 5).unwrap();
    assert_eq!(lt5.rows[0].brightness, 4);
    assert_eq!(
        lt5.rows[0].bg[1].scroll_x, 6,
        "n should have continued from frame 4 (5), not reset to 1"
    );
    assert!(
        lt5.rows[0].bg[2].scroll_x > ticks4,
        "ticks should have continued, not reset"
    );
    assert!(has_sound(e.audio()), "voice 0 should still be sounding");

    // Contrast: a real main.lua change (trailing comment) forces a full
    // recompile — init() reruns, resetting n.
    let main_changed = format!("{main}-- trailing comment\n");
    e.set_sources(&[
        ("main.lua", &main_changed),
        ("ppuglobals.lua", &controls("  brightness = 4\n")),
    ])
    .unwrap();
    let lt6 = e.frame(0.0, 6).unwrap();
    assert_eq!(
        lt6.rows[0].bg[1].scroll_x, 1,
        "init should have rerun, resetting n"
    );
}

/// (f) A syntax error in a controls-only push is refused, attributed to
/// `ppuglobals.lua`, and leaves the previously-applying controls (and all
/// program state) exactly as they were; a subsequent valid push recovers.
#[test]
fn invalid_controls_keeps_the_previous_override_and_program_state() {
    let main = voice0_main();
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("main.lua", &main),
        ("ppuglobals.lua", &controls("  brightness = 4\n")),
    ])
    .unwrap();
    for f in 0..5u32 {
        e.frame(0.0, f).unwrap();
    }

    let broken =
        "markers = {\n}\n\nscanlines = {\n}\n\nfunction apply_pokes(\n  brightness = 9\nend\n";
    let err = e
        .set_sources(&[("main.lua", &main), ("ppuglobals.lua", broken)])
        .unwrap_err();
    assert_eq!(err.file.as_deref(), Some("ppuglobals.lua"));

    let lt = e.frame(0.0, 5).unwrap();
    assert_eq!(
        lt.rows[0].brightness, 4,
        "the last valid controls should still apply"
    );
    assert_eq!(
        lt.rows[0].bg[1].scroll_x, 6,
        "n should have kept counting through the failed push"
    );

    e.set_sources(&[
        ("main.lua", &main),
        ("ppuglobals.lua", &controls("  brightness = 6\n")),
    ])
    .unwrap();
    let lt = e.frame(0.0, 6).unwrap();
    assert_eq!(lt.rows[0].brightness, 6);
    assert_eq!(lt.rows[0].bg[1].scroll_x, 7, "n should still be continuous");
}

/// (g) Toy switch (a full recompile with both files different) drops the
/// old controls override outright; a program with no ppuglobals.lua at all
/// and a legacy `pokes.lua` + explicit `apply_pokes()` call keeps working
/// unchanged (see `scanline_pokes.rs`, untouched by this ticket).
#[test]
fn toy_switch_drops_old_controls_and_legacy_pokes_lua_still_works() {
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("main.lua", "function frame(t, f) end"),
        ("ppuglobals.lua", &controls("  brightness = 12\n")),
    ])
    .unwrap();
    assert_eq!(e.frame(0.0, 0).unwrap().rows[0].brightness, 12);

    e.set_sources(&[
        ("main.lua", "function frame(t, f) TM = 0x01 end"),
        ("ppuglobals.lua", &controls("  bg[1].scroll.x = 5\n")),
    ])
    .unwrap();
    let lt = e.frame(0.0, 0).unwrap();
    assert_eq!(
        lt.rows[0].brightness, 15,
        "the OLD controls override must be gone (power-on default)"
    );
    assert_eq!(
        lt.rows[0].bg[0].scroll_x, 5,
        "the NEW controls should apply"
    );

    let mut legacy = LuaEngine::new();
    legacy
        .set_sources(&[
            ("pokes.lua", "function apply_pokes() brightness = 2 end"),
            ("main.lua", "function frame(t, f) apply_pokes() end"),
        ])
        .unwrap();
    assert_eq!(legacy.frame(0.0, 0).unwrap().rows[0].brightness, 2);
}

/// (h) A runtime error inside `apply_pokes` surfaces through the same
/// `LuaError` shape as any other hook error, attributed to `ppuglobals.lua`,
/// and never touches the program's own globals — the next successful frame
/// continues the program's accumulator right where the errored one left it.
#[test]
fn runtime_error_inside_apply_pokes_is_attributed_and_program_state_stays_clean() {
    let main = "function frame(t, f) n = (n or 0) + 1; bg[2].scroll.x = n end";
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("main.lua", main),
        ("ppuglobals.lua", &controls("  nothing.x = 1\n")),
    ])
    .unwrap();
    let err = e.frame(0.0, 0).unwrap_err();
    assert_eq!(err.file.as_deref(), Some("ppuglobals.lua"));

    e.set_sources(&[
        ("main.lua", main),
        ("ppuglobals.lua", &controls("  brightness = 7\n")),
    ])
    .unwrap();
    let lt = e.frame(0.0, 1).unwrap();
    assert_eq!(lt.rows[0].brightness, 7);
    assert_eq!(
        lt.rows[0].bg[1].scroll_x, 2,
        "n should have continued across the errored frame (1 -> 2)"
    );
}

/// ppuglobals.lua runs before every user chunk regardless of its position in
/// the list: a `markers.<name>` reference pasted at a user file's top level
/// (the Timeline panel's copy chip) resolves, and `apply_pokes` is callable
/// from a top-level statement too.
#[test]
fn controls_chunk_runs_before_user_chunks_wherever_it_is_listed() {
    let doc =
        controls("  brightness = 3\n").replace("markers = {\n}", "markers = {\n  intro = 2.5,\n}");
    let main = "at = markers.intro\nfunction frame(t, f) bg[2].scroll.x = at * 2 end";
    let mut e = LuaEngine::new();
    e.set_sources(&[("main.lua", main), ("ppuglobals.lua", &doc)])
        .expect("markers must already exist when main.lua's top level runs");
    let lt = e.frame(0.0, 0).unwrap();
    assert_eq!(lt.rows[0].bg[1].scroll_x, 5);
    assert_eq!(lt.rows[0].brightness, 3);
}

/// (i) A program `hdma` hook missing its function argument (a typo'd
/// `hdma(0, 100)`) must not desync the splice index from the collected
/// hooks Vec — only FUNCTION-bearing `__ppu_hooks` entries are ever
/// collected, so `n_program` must count the same way or the splice index
/// can go out of range. Also proves splice ordering: the frame-wide
/// controls override beats the program's own hdma hook, and controls's own
/// band hook (registered by `apply_pokes` itself) beats the frame-wide
/// override in turn.
#[test]
fn program_hook_missing_its_function_argument_does_not_desync_the_splice_index() {
    let main = "function frame(t, f)\n\
                  brightness = 9\n\
                  hdma(0, 100)\n\
                  hdma(100, 150, function(y) bg[1].scroll.x = 7 end)\n\
                end\n";
    let doc = controls_with_scanlines(
        "  water = { first = 120, last = 223 },\n",
        "  bg[1].scroll.x = 24\n\
         hdma(scanlines.water.first, scanlines.water.last, function(y)\n\
           bg[1].scroll.x = 2\n\
         end)\n",
    );
    let mut e = LuaEngine::new();
    e.set_sources(&[("main.lua", main), ("ppuglobals.lua", &doc)])
        .unwrap();
    for f in 0..2u32 {
        let lt = e.frame(0.0, f).unwrap();
        assert_eq!(lt.rows[10].bg[0].scroll_x, 24, "frame {f}");
        assert_eq!(
            lt.rows[110].bg[0].scroll_x, 24,
            "frame {f}: frame-wide beats the program hook"
        );
        assert_eq!(
            lt.rows[125].bg[0].scroll_x, 2,
            "frame {f}: controls band beats frame-wide"
        );
        assert_eq!(lt.rows[110].brightness, 9, "frame {f}");
    }
}

/// (j) An explicit `apply_pokes()` call from inside the program's own
/// `frame()` runs under the same tracked env Phase A uses, so its writes
/// must be logged and undone by the same end-of-frame restore — not
/// discarded (old bug) or left to bake in permanently.
#[test]
fn explicit_apply_pokes_call_inside_program_frame_does_not_escape_the_undo_log() {
    let main = "function frame(t, f)\n\
                  x = (x or 0) + 1\n\
                  bg[1].scroll.x = x\n\
                  obj[0].x = obj[0].x + 1\n\
                  apply_pokes()\n\
                end\n";
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("main.lua", main),
        (
            "ppuglobals.lua",
            &controls("  bg[1].scroll.x = 100\n  obj[0].x = 96\n"),
        ),
    ])
    .unwrap();
    for f in 0..5u32 {
        let lt = e.frame(0.0, f).unwrap();
        assert_eq!(
            lt.rows[0].bg[0].scroll_x, 100,
            "frame {f}: override visible"
        );
        assert_eq!(e.memory().oam[0].x, 96, "frame {f}: override visible");
    }

    e.set_sources(&[("main.lua", main), ("ppuglobals.lua", &controls(""))])
        .unwrap();
    for f in 5..7u32 {
        e.frame(0.0, f).unwrap();
    }
    assert_eq!(
        e.memory().oam[0].x,
        7,
        "the explicit apply_pokes() call's writes must have been undone every frame, \
         so the program's own accumulator progressed by exactly 1/frame (7), not 98"
    );
}

/// (k) A fast-path controls push that fails at RUNTIME partway through
/// (after some top-level writes already landed on the real globals) must be
/// fully unwound: the previous good controls keep applying, and the
/// program can still read the previous good `markers` — not the failed
/// push's partial redefinition.
#[test]
fn fast_path_runtime_error_midway_through_controls_is_fully_undone() {
    let main = "function frame(t, f) bg[2].scroll.x = markers.intro * 2 end";
    let doc =
        controls("  brightness = 4\n").replace("markers = {\n}", "markers = {\n  intro = 2.5,\n}");
    let mut e = LuaEngine::new();
    e.set_sources(&[("main.lua", main), ("ppuglobals.lua", &doc)])
        .unwrap();
    let lt = e.frame(0.0, 0).unwrap();
    assert_eq!(lt.rows[0].brightness, 4);
    assert_eq!(lt.rows[0].bg[1].scroll_x, 5);

    let broken =
        "markers = {\n  intro = 9,\n}\n\nscanlines = {\n}\n\nlocal boom = nil\nboom.x = 1\n";
    let err = e
        .set_sources(&[("main.lua", main), ("ppuglobals.lua", broken)])
        .unwrap_err();
    assert_eq!(err.file.as_deref(), Some("ppuglobals.lua"));

    let lt = e.frame(0.0, 1).unwrap();
    assert_eq!(
        lt.rows[0].brightness, 4,
        "the last valid controls should still apply"
    );
    assert_eq!(
        lt.rows[0].bg[1].scroll_x, 5,
        "markers.intro must have been restored to 2.5, not left at the failed push's 9"
    );
}

/// (l) A fast-path controls push whose text no longer defines
/// `apply_pokes` must clear the previously-stashed function, not silently
/// keep re-applying the old chunk's override.
#[test]
fn fast_path_controls_push_without_apply_pokes_clears_the_stashed_override() {
    let main = "function frame(t, f) brightness = 5 end";
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("main.lua", main),
        ("ppuglobals.lua", &controls("  brightness = 12\n")),
    ])
    .unwrap();
    assert_eq!(e.frame(0.0, 0).unwrap().rows[0].brightness, 12);

    let no_apply_pokes = "markers = {\n}\n\nscanlines = {\n}\n";
    e.set_sources(&[("main.lua", main), ("ppuglobals.lua", no_apply_pokes)])
        .unwrap();
    assert_eq!(
        e.frame(0.0, 1).unwrap().rows[0].brightness,
        5,
        "no apply_pokes in the new text: the override must be gone"
    );
}

/// (m) A program that still calls `apply_pokes()` explicitly after a
/// fast-path push clears it gets a runtime error attributed to ITS OWN
/// file, not `ppuglobals.lua` — the global is genuinely nil, not silently
/// re-stashed from the previous chunk.
#[test]
fn explicit_apply_pokes_call_after_fast_path_clear_errors_on_the_callers_own_file() {
    let calls_it = "function frame(t, f) apply_pokes() end";
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("main.lua", calls_it),
        ("ppuglobals.lua", &controls("  brightness = 12\n")),
    ])
    .unwrap();
    let no_apply_pokes = "markers = {\n}\n\nscanlines = {\n}\n";
    e.set_sources(&[("main.lua", calls_it), ("ppuglobals.lua", no_apply_pokes)])
        .unwrap();
    let err = e.frame(0.0, 0).unwrap_err();
    assert_eq!(err.file.as_deref(), Some("main.lua"));
}

/// An error exit from the program's own `frame()` body — right after
/// an explicit `apply_pokes()` call it made — must restore the controls
/// undo log before returning, or that call's writes bake in permanently:
/// the next frame's `__ppu_controls_begin` discards the stale log without
/// ever undoing it.
#[test]
fn program_frame_error_after_explicit_apply_pokes_restores_the_undo_log() {
    let main = "function frame(t, f)\n\
                  obj[0].x = obj[0].x + 1\n\
                  apply_pokes()\n\
                  if f == 2 then error(\"boom\") end\n\
                end\n";
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("main.lua", main),
        ("ppuglobals.lua", &controls("  obj[0].x = 96\n")),
    ])
    .unwrap();

    for f in 0..=4u32 {
        let res = e.frame(0.0, f);
        if f == 2 {
            assert_eq!(res.unwrap_err().file.as_deref(), Some("main.lua"));
        } else {
            res.unwrap();
        }
    }

    e.set_sources(&[("main.lua", main), ("ppuglobals.lua", &controls(""))])
        .unwrap();
    for f in 5..=7u32 {
        e.frame(0.0, f).unwrap();
    }
    // Every frame 0..=4 ran its own `obj[0].x = obj[0].x + 1` exactly once,
    // including frame 2 (it errored only AFTER that increment) — 5
    // increments landed by the time controls is released at frame 5.
    // Frames 5,6,7 add 3 more: 5 + 3 = 8. Without the error-exit restore, frame 2's
    // explicit apply_pokes() write (96) is never undone (baked in instead
    // of restored to 3, its pre-error value), so the count instead lands at
    // 96 + 1 (frame 3) + 1 (frame 4) + 1 (frame 5) + 1 (frame 6) + 1 (frame
    // 7) = 101.
    assert_eq!(
        e.memory().oam[0].x,
        8,
        "the errored frame's explicit apply_pokes() write must have been undone"
    );
}

/// Same as above, but the explicit `apply_pokes()` call and the error
/// happen inside a `timer(...)` hook instead of `frame()`'s own body — the
/// other error exit after `__ppu_controls_begin` (through
/// `render_frame_audio`) must restore just as reliably.
#[test]
fn timer_hook_error_after_explicit_apply_pokes_restores_the_undo_log() {
    let main = "timer(0, 64, function()\n\
                  apply_pokes()\n\
                  if f_now == 2 then error(\"boom\") end\n\
                end)\n\
                function frame(t, f)\n\
                  f_now = f\n\
                  obj[0].x = obj[0].x + 1\n\
                end\n";
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("main.lua", main),
        ("ppuglobals.lua", &controls("  obj[0].x = 96\n")),
    ])
    .unwrap();

    for f in 0..=4u32 {
        let res = e.frame(0.0, f);
        if f == 2 {
            assert_eq!(res.unwrap_err().file.as_deref(), Some("main.lua"));
        } else {
            res.unwrap();
        }
    }

    e.set_sources(&[("main.lua", main), ("ppuglobals.lua", &controls(""))])
        .unwrap();
    for f in 5..=7u32 {
        e.frame(0.0, f).unwrap();
    }
    // Same arithmetic as the frame()-body variant above: 5 increments landed
    // by release (frame 2's increment ran before its timer hook errored),
    // plus 3 more after release = 8, not 101.
    assert_eq!(
        e.memory().oam[0].x,
        8,
        "the timer hook's explicit apply_pokes() write must have been undone"
    );
}

/// The end-of-frame restore must undo controls's writes BEFORE
/// re-baselining sticky globals to the frame-wide defaults, not after: a
/// controls BAND hook's first logged write for a key carries that row's
/// `write_state(row)` baseline as its "old" value, not the frame-wide
/// default, so restoring AFTER `write_state(&defaults)` clobbers the
/// program's own accumulator with a stray per-row value.
#[test]
fn controls_restore_runs_before_the_sticky_defaults_rebaseline() {
    let main = "function frame(t, f)\n\
                  bg[1].scroll.x = bg[1].scroll.x + 1\n\
                  bg[2].scroll.x = bg[1].scroll.x\n\
                  hdma(0, 10, function(y) bg[1].scroll.x = 0 end)\n\
                end\n";
    let doc = controls_with_scanlines(
        "  water = { first = 5, last = 8 },\n",
        "  hdma(scanlines.water.first, scanlines.water.last, function(y)\n\
           bg[1].scroll.x = 50\n\
         end)\n",
    );
    let mut e = LuaEngine::new();
    e.set_sources(&[("main.lua", main), ("ppuglobals.lua", &doc)])
        .unwrap();
    e.frame(0.0, 0).unwrap();
    let lt = e.frame(0.0, 1).unwrap();

    assert_eq!(
        lt.rows[0].bg[1].scroll_x, 2,
        "the program's own accumulator (mirrored into bg[2], which nothing \
         pokes) should have advanced 1 -> 2 across the two frames; with the \
         restore-after-rebaseline bug it reads 1"
    );
    assert_eq!(
        lt.rows[6].bg[0].scroll_x, 50,
        "inside the controls band, the band hook still wins"
    );
    assert_eq!(
        lt.rows[0].bg[0].scroll_x, 0,
        "outside the band but inside the program's own hdma, its hook still wins"
    );

    // Baseline sanity: the same program with no ppuglobals.lua at all must
    // reach the same accumulator value, proving the 2 above is the program's
    // own arithmetic and not an artifact of controls.
    let mut plain = LuaEngine::new();
    plain.set_sources(&[("main.lua", main)]).unwrap();
    plain.frame(0.0, 0).unwrap();
    let lt = plain.frame(0.0, 1).unwrap();
    assert_eq!(lt.rows[0].bg[1].scroll_x, 2);
}

// PPU-148: named-band HDMA (`scanlines.<name>` + `hdma(...)` calls inside
// `apply_pokes`) — deterministic scope and overlap. Every program below sets
// a known frame-wide baseline so "program value" below is always a
// hand-derived literal, never a value read back from the engine.

/// (a) A band's [first,last] range is inclusive on both ends, and a
/// single-line band ([y,y]) touches exactly that row, not its neighbors.
#[test]
fn bands_are_inclusive_and_a_single_line_band_touches_exactly_that_row() {
    let main = "function frame(t, f)\n  brightness = 9\n  bg[1].scroll.x = 0\n  mode = 1\nend\n";
    let doc = controls_with_scanlines(
        "  top = { first = 0, last = 0 },\n\
         mid = { first = 100, last = 100 },\n\
         bottom = { first = 223, last = 223 },\n",
        "  hdma(scanlines.top.first, scanlines.top.last, function(y)\n\
           brightness = 1\n\
         end)\n\
         hdma(scanlines.mid.first, scanlines.mid.last, function(y)\n\
           brightness = 2\n\
         end)\n\
         hdma(scanlines.bottom.first, scanlines.bottom.last, function(y)\n\
           brightness = 3\n\
         end)\n",
    );
    let mut e = LuaEngine::new();
    e.set_sources(&[("main.lua", main), ("ppuglobals.lua", &doc)])
        .unwrap();
    let lt = e.frame(0.0, 0).unwrap();
    assert_eq!(lt.rows[0].brightness, 1, "top band touches row 0");
    assert_eq!(lt.rows[100].brightness, 2, "mid band touches row 100");
    assert_eq!(lt.rows[223].brightness, 3, "bottom band touches row 223");
    for y in [1usize, 99, 101, 222] {
        assert_eq!(
            lt.rows[y].brightness, 9,
            "row {y}: outside every band, the program value holds"
        );
    }

    // A full-height [0,223] band covers every single row, no gaps at either edge.
    let doc_full = controls_with_scanlines(
        "  full = { first = 0, last = 223 },\n",
        "  hdma(scanlines.full.first, scanlines.full.last, function(y)\n\
           brightness = 4\n\
         end)\n",
    );
    let mut e2 = LuaEngine::new();
    e2.set_sources(&[("main.lua", main), ("ppuglobals.lua", &doc_full)])
        .unwrap();
    let lt2 = e2.frame(0.0, 0).unwrap();
    for y in 0..224usize {
        assert_eq!(
            lt2.rows[y].brightness, 4,
            "row {y}: full-height band covers it"
        );
    }
}

/// (b) Two overlapping bands: a later-registered band wins ONLY for a
/// property both write on the overlapping lines; a property only the
/// earlier band writes survives untouched there. Swapping registration
/// order (and the scanlines table order with it) swaps which band wins the
/// shared property.
#[test]
fn overlapping_bands_later_wins_only_the_shared_property() {
    let main = "function frame(t, f)\n  brightness = 9\n  bg[1].scroll.x = 0\n  mode = 1\nend\n";
    let doc_ab = controls_with_scanlines(
        "  a = { first = 100, last = 150 },\n  b = { first = 120, last = 200 },\n",
        "  hdma(scanlines.a.first, scanlines.a.last, function(y)\n\
           bg[1].scroll.x = 1\n\
           brightness = 5\n\
         end)\n\
         hdma(scanlines.b.first, scanlines.b.last, function(y)\n\
           bg[1].scroll.x = 2\n\
         end)\n",
    );
    let mut e = LuaEngine::new();
    e.set_sources(&[("main.lua", main), ("ppuglobals.lua", &doc_ab)])
        .unwrap();
    let lt = e.frame(0.0, 0).unwrap();
    assert_eq!(lt.rows[110].bg[0].scroll_x, 1, "row 110: only A covers it");
    assert_eq!(lt.rows[110].brightness, 5, "row 110: only A covers it");
    assert_eq!(
        lt.rows[130].bg[0].scroll_x, 2,
        "row 130: B registered later, wins the shared property"
    );
    assert_eq!(
        lt.rows[130].brightness, 5,
        "row 130: brightness is A-only, untouched by B"
    );
    assert_eq!(lt.rows[160].bg[0].scroll_x, 2, "row 160: only B covers it");
    assert_eq!(
        lt.rows[160].brightness, 9,
        "row 160: neither band writes brightness there"
    );
    for y in [90usize, 210] {
        assert_eq!(lt.rows[y].bg[0].scroll_x, 0, "row {y}: outside both bands");
        assert_eq!(lt.rows[y].brightness, 9, "row {y}: outside both bands");
    }

    // Same doc, hooks (and table rows) in the opposite order: B first, A second.
    let doc_ba = controls_with_scanlines(
        "  b = { first = 120, last = 200 },\n  a = { first = 100, last = 150 },\n",
        "  hdma(scanlines.b.first, scanlines.b.last, function(y)\n\
           bg[1].scroll.x = 2\n\
         end)\n\
         hdma(scanlines.a.first, scanlines.a.last, function(y)\n\
           bg[1].scroll.x = 1\n\
           brightness = 5\n\
         end)\n",
    );
    let mut e2 = LuaEngine::new();
    e2.set_sources(&[("main.lua", main), ("ppuglobals.lua", &doc_ba)])
        .unwrap();
    let lt2 = e2.frame(0.0, 0).unwrap();
    assert_eq!(
        lt2.rows[130].bg[0].scroll_x, 1,
        "reordered: A is now registered last, so it wins the shared property at row 130"
    );
    assert_eq!(lt2.rows[130].brightness, 5);
}

/// (c) A band beats the program's own authored `hdma` only where the band
/// itself writes; a whole-frame controls override in turn beats the
/// program's authored hdma everywhere it doesn't overlap a band, with the
/// band still winning only where it writes on top of that.
#[test]
fn band_beats_authored_hdma_only_where_it_writes() {
    let main = "function frame(t, f)\n\
                  brightness = 9\n\
                  bg[1].scroll.x = 0\n\
                  mode = 1\n\
                  hdma(100, 150, function(y)\n\
                    bg[1].scroll.x = 7\n\
                    brightness = 3\n\
                  end)\n\
                end\n";
    let doc = controls_with_scanlines(
        "  band = { first = 120, last = 223 },\n",
        "  hdma(scanlines.band.first, scanlines.band.last, function(y)\n\
           bg[1].scroll.x = 2\n\
         end)\n",
    );
    let mut e = LuaEngine::new();
    e.set_sources(&[("main.lua", main), ("ppuglobals.lua", &doc)])
        .unwrap();
    let lt = e.frame(0.0, 0).unwrap();
    assert_eq!(lt.rows[130].bg[0].scroll_x, 2, "row 130: band wins scroll");
    assert_eq!(
        lt.rows[130].brightness, 3,
        "row 130: the band never wrote brightness, main's hdma value stands"
    );
    assert_eq!(
        lt.rows[110].bg[0].scroll_x, 7,
        "row 110: outside the band, main's hdma stands"
    );
    assert_eq!(lt.rows[110].brightness, 3, "row 110: main's hdma value");
    assert_eq!(
        lt.rows[160].bg[0].scroll_x, 2,
        "row 160: band wins, outside main's own hdma"
    );
    assert_eq!(
        lt.rows[160].brightness, 9,
        "row 160: program frame-wide brightness, nothing else touches it"
    );

    // Add a frame-wide `brightness = 12` to controls: it beats main's own
    // hdma everywhere; the band still wins scroll only where it writes.
    let doc2 = controls_with_scanlines(
        "  band = { first = 120, last = 223 },\n",
        "  brightness = 12\n\
         hdma(scanlines.band.first, scanlines.band.last, function(y)\n\
           bg[1].scroll.x = 2\n\
         end)\n",
    );
    let mut e2 = LuaEngine::new();
    e2.set_sources(&[("main.lua", main), ("ppuglobals.lua", &doc2)])
        .unwrap();
    let lt2 = e2.frame(0.0, 0).unwrap();
    assert_eq!(
        lt2.rows[110].brightness, 12,
        "frame-wide beats the program's own hdma"
    );
    assert_eq!(
        lt2.rows[130].brightness, 12,
        "frame-wide beats it here too; the band doesn't write brightness"
    );
    assert_eq!(
        lt2.rows[110].bg[0].scroll_x, 7,
        "scroll unchanged from before: row 110 is outside the band"
    );
    assert_eq!(
        lt2.rows[130].bg[0].scroll_x, 2,
        "scroll unchanged from before: the band still wins here"
    );
}

/// (d) A band's relative write must apply exactly once per row per frame —
/// never twice, which a duplicate hook across fast-path reloads, or a stale
/// hook left behind after remove/resize/rename, would produce — across
/// several frames, and survive a run of fast-path (controls-only) edits:
/// remove, disable, resize, and rename the band. (The `__ppu_hooks` nil-clear
/// in lua.rs's `frame()` is NOT observable here — its dead entries were never
/// read — and is pinned by nothing, by design: these tests never reach into
/// the VM.)
#[test]
fn band_edits_over_the_fast_path_leave_no_stale_or_duplicate_effect() {
    let main = "function frame(t, f)\n\
                  brightness = 9\n\
                  bg[1].scroll.x = 10\n\
                  mode = 1\n\
                end\n";
    let doc = controls_with_scanlines(
        "  a = { first = 100, last = 150 },\n",
        "  hdma(scanlines.a.first, scanlines.a.last, function(y)\n\
           bg[1].scroll.x = bg[1].scroll.x + 1\n\
         end)\n",
    );
    let mut e = LuaEngine::new();
    e.set_sources(&[("main.lua", main), ("ppuglobals.lua", &doc)])
        .unwrap();
    for f in 0..3u32 {
        let lt = e.frame(0.0, f).unwrap();
        for y in 100..=150usize {
            assert_eq!(
                lt.rows[y].bg[0].scroll_x, 11,
                "frame {f} row {y}: exactly +1, never +2"
            );
        }
        for y in [50usize, 200] {
            assert_eq!(
                lt.rows[y].bg[0].scroll_x, 10,
                "frame {f} row {y}: outside the band"
            );
        }
    }

    // Fast path: remove the band entirely (ppuglobals.lua changes, main.lua doesn't).
    let doc_removed = controls_with_scanlines("  a = { first = 100, last = 150 },\n", "");
    e.set_sources(&[("main.lua", main), ("ppuglobals.lua", &doc_removed)])
        .unwrap();
    let lt = e.frame(0.0, 3).unwrap();
    for y in 0..224usize {
        assert_eq!(lt.rows[y].bg[0].scroll_x, 10, "row {y}: band removed");
    }

    // Fast path: disabled band (the generated table row + guarded-hook shape).
    let doc_disabled = controls_with_scanlines(
        "  a = { first = 100, last = 150, enabled = false },\n",
        "  if scanlines.a.enabled ~= false then hdma(scanlines.a.first, scanlines.a.last, function(y)\n\
           bg[1].scroll.x = bg[1].scroll.x + 1\n\
         end) end\n",
    );
    e.set_sources(&[("main.lua", main), ("ppuglobals.lua", &doc_disabled)])
        .unwrap();
    let lt = e.frame(0.0, 4).unwrap();
    for y in 0..224usize {
        assert_eq!(lt.rows[y].bg[0].scroll_x, 10, "row {y}: band disabled");
    }

    // Fast path: resize 100..150 -> 160..200.
    let doc_resized = controls_with_scanlines(
        "  a = { first = 160, last = 200 },\n",
        "  hdma(scanlines.a.first, scanlines.a.last, function(y)\n\
           bg[1].scroll.x = bg[1].scroll.x + 1\n\
         end)\n",
    );
    e.set_sources(&[("main.lua", main), ("ppuglobals.lua", &doc_resized)])
        .unwrap();
    let lt = e.frame(0.0, 5).unwrap();
    for y in 100..=150usize {
        assert_eq!(
            lt.rows[y].bg[0].scroll_x, 10,
            "row {y}: old range no longer touched"
        );
    }
    for y in 160..=200usize {
        assert_eq!(
            lt.rows[y].bg[0].scroll_x, 11,
            "row {y}: new range, exactly +1"
        );
    }

    // Fast path: rename a -> sea (table row + every hook reference).
    let doc_renamed = controls_with_scanlines(
        "  sea = { first = 160, last = 200 },\n",
        "  hdma(scanlines.sea.first, scanlines.sea.last, function(y)\n\
           bg[1].scroll.x = bg[1].scroll.x + 1\n\
         end)\n",
    );
    e.set_sources(&[("main.lua", main), ("ppuglobals.lua", &doc_renamed)])
        .unwrap();
    let lt = e.frame(0.0, 6).unwrap();
    for y in 160..=200usize {
        assert_eq!(
            lt.rows[y].bg[0].scroll_x, 11,
            "row {y}: renamed band, still exactly +1"
        );
    }
}

/// (e) A band's CGRAM poke lands only on the rows it covers, and a
/// frame-wide CGRAM poke (already baked into the Phase A snapshot) is not
/// re-reported as a per-row poke by the synthetic whole-frame hook.
#[test]
fn band_cgram_poke_lands_only_on_its_rows_and_frame_wide_cgram_is_not_re_reported() {
    let main = "function frame(t, f)\n  brightness = 9\n  mode = 1\nend\n";
    let doc = controls_with_scanlines(
        "  band = { first = 50, last = 60 },\n",
        "  hdma(scanlines.band.first, scanlines.band.last, function(y)\n\
           cgram[1] = 0x7fff\n\
         end)\n",
    );
    let mut e = LuaEngine::new();
    e.set_sources(&[("main.lua", main), ("ppuglobals.lua", &doc)])
        .unwrap();
    let lt = e.frame(0.0, 0).unwrap();
    assert!(
        lt.rows[55].cgram.contains(&(1, 0x7fff)),
        "row 55: inside the band, the poke is recorded"
    );
    assert!(
        lt.rows[50].cgram.contains(&(1, 0x7fff)),
        "row 50: band's first row (inclusive edge)"
    );
    assert!(
        lt.rows[60].cgram.contains(&(1, 0x7fff)),
        "row 60: band's last row (inclusive edge)"
    );
    assert!(
        !lt.rows[49].cgram.iter().any(|&(i, _)| i == 1),
        "row 49: outside the band, no poke recorded"
    );
    assert!(
        !lt.rows[61].cgram.iter().any(|&(i, _)| i == 1),
        "row 61: outside the band, no poke recorded"
    );

    let doc2 = controls("  cgram[2] = 0x1234\n");
    let mut e2 = LuaEngine::new();
    e2.set_sources(&[("main.lua", main), ("ppuglobals.lua", &doc2)])
        .unwrap();
    let lt2 = e2.frame(0.0, 0).unwrap();
    assert_eq!(e2.memory().cgram[2], 0x1234);
    for y in 0..224usize {
        assert!(
            !lt2.rows[y].cgram.iter().any(|&(i, _)| i == 2),
            "row {y}: frame-wide cgram write must not be re-reported per-row"
        );
    }
}

/// (f) A keyframe curve (`pki` tables computing per-row values) inside a
/// band survives, producing byte-identical numbers to the plain
/// (non-band) generated document pinned in `scanline_pokes.rs`'s
/// `GENERATED`.
#[test]
fn existing_keyframe_curves_survive_inside_a_band() {
    let doc = controls_with_curve(
        "  full = { first = 0, last = 223 },\n",
        "  hdma(scanlines.full.first, scanlines.full.last, function(y)\n\
           win.w1.hi = pki({{0,128},{112,198},{223,128}}, y)\n\
           win.w1.lo = pki({{0,128},{112,58},{223,128}}, y)\n\
         end)\n",
    );
    // No explicit apply_pokes() call: ppuglobals.lua's Phase A applies it
    // automatically, unlike the legacy pokes.lua path in scanline_pokes.rs.
    let main = "function frame(t, f)\n  mode = 1\n  brightness = 15\nend\n";
    let mut e = LuaEngine::new();
    e.set_sources(&[("main.lua", main), ("ppuglobals.lua", &doc)])
        .unwrap();
    let lt = e.frame(0.0, 0).unwrap();
    let bytes = ppu_core::window_scanline_bytes(&lt);
    let edges = |y: usize| {
        (
            bytes[y * ppu_core::WIN_SCANLINE_STRIDE],
            bytes[y * ppu_core::WIN_SCANLINE_STRIDE + 1],
        )
    };
    assert_eq!(edges(0), (128, 128), "first keyframe");
    assert_eq!(edges(112), (58, 198), "middle keyframe");
    assert_eq!(edges(223), (128, 128), "last keyframe");
    assert_eq!(edges(56), (93, 163), "linear midpoint");
    assert_eq!(
        edges(1).0,
        127,
        "fractional interpolation must round, not drop"
    );
}

/// (g) Ramps round integer registers exactly (`floor(v+0.5)`, per `pki`)
/// and keep Mode 7's fractional Q8.8 registers (`pkf`, no rounding).
#[test]
fn ramps_round_integers_exactly_and_keep_mode7_fractions() {
    let main = "function frame(t, f)\n  brightness = 9\n  mode = 7\nend\n";
    let doc = controls_with_curve(
        "  band = { first = 100, last = 103 },\n",
        "  hdma(scanlines.band.first, scanlines.band.last, function(y)\n\
           brightness = pki({{100,0},{103,1}}, y)\n\
         end)\n",
    );
    let mut e = LuaEngine::new();
    e.set_sources(&[("main.lua", main), ("ppuglobals.lua", &doc)])
        .unwrap();
    let lt = e.frame(0.0, 0).unwrap();
    assert_eq!(lt.rows[100].brightness, 0, "0 -> floor(0.5) = 0");
    assert_eq!(lt.rows[101].brightness, 0, "0.333 -> floor(0.833) = 0");
    assert_eq!(lt.rows[102].brightness, 1, "0.667 -> floor(1.167) = 1");
    assert_eq!(lt.rows[103].brightness, 1, "1 -> floor(1.5) = 1");

    let doc_m7 = controls_with_curve(
        "  full = { first = 0, last = 223 },\n",
        "  hdma(scanlines.full.first, scanlines.full.last, function(y)\n\
           m7.a = pkf({{0,1},{223,2}}, y)\n\
         end)\n",
    );
    let mut e2 = LuaEngine::new();
    e2.set_sources(&[("main.lua", main), ("ppuglobals.lua", &doc_m7)])
        .unwrap();
    let lt2 = e2.frame(0.0, 0).unwrap();
    assert_eq!(lt2.rows[0].m7.a, 0x100, "y=0: a=1.0 in Q8.8");
    assert_eq!(lt2.rows[223].m7.a, 0x200, "y=223: a=2.0 in Q8.8");
    // y=111: a = 1 + 111/223 = 1.49776…; × 256 = 383.43 -> round = 383 = 0x17f
    // (m7_matrix rounds to nearest, per quantize.rs).
    assert_eq!(
        lt2.rows[111].m7.a, 0x17f,
        "fractional lerp reached the Q8.8 register"
    );
}

/// (h) A single-line ramp (two keyframes at the same y) is defined and
/// never divides by zero — `pk`'s first-keyframe short-circuit
/// (`y <= kf[1][1]`) returns the first keyframe's value before the
/// zero-width-interval branch is ever reached.
#[test]
fn a_single_line_ramp_is_defined_and_never_divides() {
    let main = "function frame(t, f)\n  brightness = 9\nend\n";
    let doc = controls_with_curve(
        "  band = { first = 100, last = 100 },\n",
        "  hdma(scanlines.band.first, scanlines.band.last, function(y)\n\
           brightness = pki({{100,10},{100,20}}, y)\n\
         end)\n",
    );
    let mut e = LuaEngine::new();
    e.set_sources(&[("main.lua", main), ("ppuglobals.lua", &doc)])
        .unwrap();
    let lt = e.frame(0.0, 0).unwrap();
    assert_eq!(lt.rows[100].brightness, 10);
    assert_eq!(lt.rows[99].brightness, 9);
    assert_eq!(lt.rows[101].brightness, 9);
}

/// (i) A hand-edited reversed range ([first,last] with first > last) is
/// inert at the engine — `y0 <= y && y <= y1` never holds for any y when
/// y0 > y1 — not an error; rejecting it up front is the TS codec's job, not
/// the engine's (row-independent hdma semantics are kept as-is).
#[test]
fn a_reversed_hand_edited_range_is_inert_not_an_error() {
    let main = "function frame(t, f)\n  brightness = 9\n  bg[1].scroll.x = 0\nend\n";
    let doc = controls_with_scanlines(
        "  band = { first = 200, last = 100 },\n",
        "  hdma(scanlines.band.first, scanlines.band.last, function(y)\n\
           brightness = 1\n\
           bg[1].scroll.x = 1\n\
         end)\n",
    );
    let mut e = LuaEngine::new();
    e.set_sources(&[("main.lua", main), ("ppuglobals.lua", &doc)])
        .unwrap();
    let lt = e.frame(0.0, 0).unwrap();
    for y in 0..224usize {
        assert_eq!(
            lt.rows[y].brightness, 9,
            "row {y}: reversed band never applies"
        );
        assert_eq!(
            lt.rows[y].bg[0].scroll_x, 0,
            "row {y}: reversed band never applies"
        );
    }
}

#[test]
fn legacy_generated_name_is_supported_but_user_controls_are_ordinary_code() {
    let mut e = LuaEngine::new();
    let old = controls("  brightness = 12\n").replacen("-- ppuglobals.lua", "-- controls.lua", 1);
    let main = "function frame(t, f) brightness = 5 end";
    e.set_sources(&[("controls.lua", &old), ("main.lua", main)])
        .unwrap();
    assert_eq!(e.frame(0.0, 0).unwrap().rows[0].brightness, 12);

    let user = "function read_controls() return 7 end";
    e.set_sources(&[
        ("ppuglobals.lua", &controls("")),
        ("controls.lua", user),
        (
            "main.lua",
            "function frame(t, f) brightness = read_controls() end",
        ),
    ])
    .unwrap();
    assert_eq!(e.frame(0.0, 1).unwrap().rows[0].brightness, 7);
}

/// The synthetic whole-frame hook replays only the REGISTER writes Phase A
/// logged, once per row, instead of re-executing apply_pokes 224x per
/// frame: a frame-wide register poke still overrides the program's own hdma
/// hook on every row (even one that writes the frame-wide default back),
/// while thousands of frame-only `vram[]` pokes (a tilemap paint) cost one
/// execution per frame, not 224.
#[test]
fn frame_wide_pokes_replay_per_row_without_rerunning_apply_pokes() {
    let main = "function frame(t, f)\n\
                  bg[1].scroll.x = 7\n\
                  hdma(0, 10, function(y) bg[1].scroll.x = 0; brightness = 3 end)\n\
                end\n";
    let mut body = String::from("  bg[1].scroll.x = 7\n  brightness = 15\n");
    for i in 0..4000 {
        body += &format!(
            "  vram[0x{:x}] = 0x{:x} -- tilemap cell\n",
            0x1000 + i,
            i & 0x3ff
        );
    }
    let mut e = LuaEngine::new();
    e.set_sources(&[("main.lua", main), ("ppuglobals.lua", &controls(&body))])
        .unwrap();
    let t0 = std::time::Instant::now();
    let lt = e.frame(0.0, 0).unwrap();
    let elapsed = t0.elapsed();
    assert_eq!(
        lt.rows[5].bg[0].scroll_x, 7,
        "controls override wins over the program hook"
    );
    assert_eq!(
        lt.rows[5].brightness, 15,
        "controls override wins over the program hook"
    );
    assert_eq!(lt.rows[100].bg[0].scroll_x, 7);
    assert_eq!(
        e.memory().vram[0x1000 + 3999],
        3999 & 0x3ff,
        "frame-only pokes still land"
    );
    assert!(
        elapsed < std::time::Duration::from_secs(2),
        "4000 frame-wide pokes took {elapsed:?}: apply_pokes is being re-run per row again"
    );
}

/// `controls` with a `dma(...)` line at the document's top level, between
/// the scanlines table and `apply_pokes` — the shape the DMA panel emits.
fn controls_with_dma(dma_line: &str, body: &str) -> String {
    controls(body).replace(
        "\nfunction apply_pokes()",
        &format!("{dma_line}\n\nfunction apply_pokes()"),
    )
}

fn solid_green() -> Vec<u8> {
    [0u8, 255, 0, 255].repeat(256 * 224)
}

/// A `dma()` at ppuglobals.lua's top level places the source exactly like
/// one in main.lua: recorded in the memory map and replayed into VRAM.
#[test]
fn controls_top_level_dma_places_the_source() {
    let mut e = LuaEngine::new();
    common::add_bg(&mut e, "sky", solid_green(), 256, 224, 4);
    e.set_sources(&[
        ("main.lua", "function frame(t, f) end"),
        (
            "ppuglobals.lua",
            &controls_with_dma("dma(\"sky\", { char = 0x1000, map = 0x0, pal = 0 })", ""),
        ),
    ])
    .unwrap();
    e.frame(0.0, 0).unwrap();
    let map = e.memory_map();
    assert_eq!(map.placements.len(), 1);
    assert_eq!(map.placements[0].name, "sky");
    assert_eq!(map.placements[0].char, 0x1000);
    assert_eq!(map.placements[0].map, 0);
    assert!(map
        .vram
        .iter()
        .any(|r| r.name == "sky" && r.start == 0x1000));
    assert!(map.cgram.iter().any(|r| r.name == "sky" && r.start == 0));
    assert!(
        e.memory().vram[0x1010..0x1020].iter().any(|&w| w != 0),
        "placed chars should land in VRAM (tile 0 is the reserved blank; tile 1 is the green one)"
    );
}

/// Changing a controls document's `dma(` line must recompile (the init
/// window is the only place `dma()` runs); an apply_pokes-only change must
/// still take the hot fast path (init does not rerun).
#[test]
fn controls_dma_line_change_recompiles_but_poke_change_stays_hot() {
    let main = "function init() n = 0 end\n\
                function frame(t, f) n = n + 1; bg[2].scroll.x = n end\n";
    let sky = |map: &str| format!("dma(\"sky\", {{ char = 0x1000, map = {map}, pal = 0 }})");
    let mut e = LuaEngine::new();
    common::add_bg(&mut e, "sky", solid_green(), 256, 224, 4);
    e.set_sources(&[
        ("main.lua", main),
        ("ppuglobals.lua", &controls_with_dma(&sky("0x0"), "")),
    ])
    .unwrap();
    for f in 0..3 {
        e.frame(0.0, f).unwrap();
    }

    // apply_pokes-only change: fast path, accumulator continues 3 -> 4.
    e.set_sources(&[
        ("main.lua", main),
        (
            "ppuglobals.lua",
            &controls_with_dma(&sky("0x0"), "  brightness = 4\n"),
        ),
    ])
    .unwrap();
    let lt = e.frame(0.0, 3).unwrap();
    assert_eq!(lt.rows[0].brightness, 4);
    assert_eq!(
        lt.rows[0].bg[1].scroll_x, 4,
        "fast path must not rerun init"
    );
    assert_eq!(e.memory_map().placements[0].map, 0);

    // dma line change: accepted (not "dma runs during setup"), recompiled
    // (init reruns, n resets), new placement visible.
    e.set_sources(&[
        ("main.lua", main),
        (
            "ppuglobals.lua",
            &controls_with_dma(&sky("0x400"), "  brightness = 4\n"),
        ),
    ])
    .unwrap();
    let lt = e.frame(0.0, 4).unwrap();
    assert_eq!(lt.rows[0].bg[1].scroll_x, 1, "a dma change recompiles");
    assert_eq!(lt.rows[0].brightness, 4);
    assert_eq!(e.memory_map().placements[0].map, 0x400);
}

fn controls_with_setup(setup_body: &str, pokes_body: &str) -> String {
    controls(pokes_body).replace(
        "\nfunction apply_pokes()",
        &format!("function apply_setup()\n{setup_body}end\n\nfunction apply_pokes()"),
    )
}

/// `apply_setup()` runs after every user/data chunk AND after `init()`,
/// still inside the init window: it can reach a data chunk's global and
/// make setup-only calls (`score{}` registers a timer through `bank()`/
/// `timer()`), and its own writes land on top of init()'s.
#[test]
fn controls_apply_setup_runs_after_init_inside_the_init_window() {
    let main = "function init() n = 1 end\n\
                function frame(t, f) bg[2].scroll.x = n end\n";
    let data = "tune = { tempo = 120, rows = { { sound = 'bell', note = 'C4' } }, patterns = { A = { '4.......' } }, arrangement = { 'A' } }\n";
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("main.lua", main),
        ("tune.lua", data),
        (
            "ppuglobals.lua",
            &controls_with_setup("  played = score{ data = tune }\n  n = n + 10\n", ""),
        ),
    ])
    .expect("score{} and a data global must both resolve from apply_setup");
    let lt = e.frame(0.0, 0).unwrap();
    assert_eq!(
        lt.rows[0].bg[1].scroll_x, 11,
        "apply_setup ran after init()"
    );
}

/// An error inside `apply_setup()` is attributed to ppuglobals.lua, and the
/// next good push renders again.
#[test]
fn controls_apply_setup_error_is_attributed_and_recoverable() {
    let main = "function frame(t, f) bg[2].scroll.x = 3 end";
    let mut e = LuaEngine::new();
    let err = e
        .set_sources(&[
            ("main.lua", main),
            (
                "ppuglobals.lua",
                &controls_with_setup("  nothing.x = 1\n", ""),
            ),
        ])
        .unwrap_err();
    assert_eq!(err.file.as_deref(), Some("ppuglobals.lua"));
    e.set_sources(&[
        ("main.lua", main),
        (
            "ppuglobals.lua",
            &controls_with_setup("  ok = true\n", "  brightness = 7\n"),
        ),
    ])
    .unwrap();
    let lt = e.frame(0.0, 0).unwrap();
    assert_eq!(lt.rows[0].brightness, 7);
    assert_eq!(lt.rows[0].bg[1].scroll_x, 3);
}

/// A controls-only push that changes the `apply_setup` block recompiles
/// (init reruns), while one that only touches apply_pokes stays hot.
#[test]
fn controls_apply_setup_change_recompiles_but_poke_change_stays_hot() {
    let main = "function init() n = 0 end\n\
                function frame(t, f) n = n + 1; bg[2].scroll.x = n end\n";
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("main.lua", main),
        ("ppuglobals.lua", &controls_with_setup("  a = 1\n", "")),
    ])
    .unwrap();
    for f in 0..3 {
        e.frame(0.0, f).unwrap();
    }
    e.set_sources(&[
        ("main.lua", main),
        (
            "ppuglobals.lua",
            &controls_with_setup("  a = 1\n", "  brightness = 4\n"),
        ),
    ])
    .unwrap();
    let lt = e.frame(0.0, 3).unwrap();
    assert_eq!(lt.rows[0].brightness, 4);
    assert_eq!(
        lt.rows[0].bg[1].scroll_x, 4,
        "fast path must not rerun init"
    );
    e.set_sources(&[
        ("main.lua", main),
        (
            "ppuglobals.lua",
            &controls_with_setup("  a = 2\n", "  brightness = 4\n"),
        ),
    ])
    .unwrap();
    let lt = e.frame(0.0, 4).unwrap();
    assert_eq!(
        lt.rows[0].bg[1].scroll_x, 1,
        "an apply_setup change recompiles"
    );
    assert_eq!(lt.rows[0].brightness, 4);
}

/// `score{}` inside apply_setup reads the data chunk through the controls
/// tracking proxy, so `#tune.rows` and the per-step reads must see the real
/// table (the proxy forwards `__len`/`__pairs`): the track's sample gets
/// placed in sound RAM. Before that forwarding, `#` read as 0 and the song
/// was silently empty.
#[test]
fn controls_apply_setup_score_sees_the_data_chunk_through_the_proxy() {
    let data = "tune = { tempo = 120, rows = { { sound = 'bell', note = 'C4' } }, patterns = { A = { '4.......' } }, arrangement = { 'A' } }";
    let doc = controls_with_setup("  score{ data = tune }\n", "");
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("main.lua", "function frame(t, f) end"),
        ("tune.lua", data),
        ("ppuglobals.lua", &doc),
    ])
    .unwrap();
    let placed: Vec<String> = e
        .dsp_view()
        .samples
        .iter()
        .map(|s| s.name.clone())
        .collect();
    assert_eq!(placed, vec!["bell"]);
    e.frame(0.0, 0).unwrap();
}
