//! Automatic controls application (PPU-147): with a `controls.lua` in the
//! file list, its `apply_pokes` applies every frame as a final visual
//! override pass — registers on every line, OAM/CGRAM/VRAM in `memory()` —
//! program state is untouched by it (an override never bakes into the
//! program's own baseline or compounds an accumulator), a controls-only
//! `set_sources` never recompiles, and a broken controls edit is refused
//! while the last valid controls keep applying. Driven entirely through
//! `LuaEngine`'s public API (`set_sources`/`frame`/`memory`/`audio`,
//! `LineTable.rows[y]`) — never reaching into the VM.
use ppu_core::LuaEngine;

/// A hand-copied fixture of the document shape `web/src/studio/pokes/controls.ts`
/// (PPU-146) generates — NOT a cross-language contract test; the TS
/// generator can drift from this without either side failing here.
/// `markers`/`scanlines` stay present (empty) even when `body` doesn't use
/// them.
fn controls(body: &str) -> String {
    controls_with_scanlines("", body)
}

/// Same as `controls`, but with `scanlines_body` spliced into the
/// `scanlines = {...}` table instead of leaving it empty — for tests whose
/// `apply_pokes` references `scanlines.<name>.first`/`.last`.
fn controls_with_scanlines(scanlines_body: &str, body: &str) -> String {
    format!(
        "-- controls.lua · generated by the Studio panels. Edit values here or in the panels.\n\
         -- timeline: end=30 in=0 out=30 loop=false\n\
         -- loop markers: in= out=\n\
         markers = {{\n}}\n\
         \n\
         scanlines = {{\n{scanlines_body}}}\n\
         \n\
         function apply_pokes()\n\
         {body}\
         end\n"
    )
}

/// BRR/directory poke helpers, copied from `dsp_timers.rs` (see that file's
/// doc comment for the layout) — a sounding voice 0 for the controls-only
/// reload / invalid-controls / runtime-error tests, which must prove the DSP
/// keeps running underneath a controls-only push.
fn brr_pokes(base: u16, blocks: usize, last_header: u8) -> String {
    let mut s = String::new();
    for b in 0..blocks {
        let addr = base as usize + b * 9;
        let header = if b == blocks - 1 { last_header } else { 0xc0 };
        s += &format!("aram[{addr}] = {header}\n");
        for (i, byte) in [0x77u8, 0x77, 0x77, 0x77, 0x99, 0x99, 0x99, 0x99]
            .iter()
            .enumerate()
        {
            s += &format!("aram[{}] = {byte}\n", addr + 1 + i);
        }
    }
    s
}

fn dir_entry_pokes(index: u8, start: u16, loop_addr: u16) -> String {
    let addr = 0x0100 + index as usize * 4;
    format!(
        "aram[{a0}] = {b0}\naram[{a1}] = {b1}\naram[{a2}] = {b2}\naram[{a3}] = {b3}\n",
        a0 = addr,
        b0 = start & 0xff,
        a1 = addr + 1,
        b1 = (start >> 8) & 0xff,
        a2 = addr + 2,
        b2 = loop_addr & 0xff,
        a3 = addr + 3,
        b3 = (loop_addr >> 8) & 0xff,
    )
}

/// `main.lua` for the audio-continuity tests: `init()` pokes a 6-block
/// looping BRR sample (directory entry 0, ARAM 0x0200) and seeds `n = 0`;
/// a `timer(0, 64, ..)` counts `ticks`; `frame()` advances `n`, mirrors both
/// into `bg[2]`/`bg[3]` scroll so a test can read them back through the
/// LineTable, drives voice 0's registers every frame (matches
/// `dsp_timers.rs`'s known-good VOICE0_SETUP fields), and keys it on at f=0.
fn voice0_main() -> String {
    format!(
        "function init()\n\
           n = 0\n\
         {sample}{dir}\
         end\n\
         timer(0, 64, function() ticks = (ticks or 0) + 1 end)\n\
         function frame(t, f)\n\
           n = n + 1\n\
           bg[2].scroll.x = n\n\
           bg[3].scroll.x = ticks or 0\n\
           voice[0].sample = 0\n\
           voice[0].pitch = 0x1000\n\
           voice[0].vol.l = 127\n\
           voice[0].vol.r = 127\n\
           voice[0].adsr = {{a = 15, d = 0, s = 7, r = 0}}\n\
           dsp.mvol.l = 127\n\
           dsp.mvol.r = 127\n\
           if f == 0 then kon(0) end\n\
         end\n",
        sample = brr_pokes(0x0200, 6, 0xc3),
        dir = dir_entry_pokes(0, 0x0200, 0x0200),
    )
}

fn has_sound(audio: &[i16]) -> bool {
    audio.iter().any(|&s| s != 0)
}

/// (a) A frame-wide controls override beats the program's own per-frame
/// write; releasing it (pushing an empty `apply_pokes`) returns ownership to
/// the program on the very next frame — no `reset()` involved.
#[test]
fn frame_wide_override_beats_the_programs_own_write_and_release_returns_ownership() {
    let main = "function frame(t, f) brightness = 5 end";
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("main.lua", main),
        ("controls.lua", &controls("  brightness = 12\n")),
    ])
    .unwrap();
    let lt = e.frame(0.0, 0).unwrap();
    assert_eq!(lt.rows[0].brightness, 12);
    assert_eq!(lt.rows[223].brightness, 12);

    e.set_sources(&[("main.lua", main), ("controls.lua", &controls(""))])
        .unwrap();
    let lt = e.frame(0.0, 1).unwrap();
    assert_eq!(
        lt.rows[0].brightness, 5,
        "release should return ownership to the program"
    );
}

/// (b) Overriding an animated property and then releasing it must not bake
/// the override into the program's own baseline or compound its
/// accumulator: `obj[0].x` is both the program's OWN accumulator (it
/// increments itself) and something controls overrides — after release the
/// program's progression must be exactly what it would have been had
/// controls never run.
#[test]
fn releasing_an_override_never_bakes_in_or_compounds_the_accumulator() {
    let main = "function frame(t, f)\n\
                  x = (x or 0) + 1\n\
                  bg[1].scroll.x = x\n\
                  obj[0].x = obj[0].x + 1\n\
                end\n";
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("main.lua", main),
        (
            "controls.lua",
            &controls("  bg[1].scroll.x = 100\n  obj[0].x = 96\n"),
        ),
    ])
    .unwrap();

    for f in 0..5u32 {
        let lt = e.frame(0.0, f).unwrap();
        assert_eq!(
            lt.rows[0].bg[0].scroll_x, 100,
            "frame {f}: override should be visible"
        );
        assert_eq!(
            e.memory().oam[0].x,
            96,
            "frame {f}: override should be visible in memory"
        );
    }

    e.set_sources(&[("main.lua", main), ("controls.lua", &controls(""))])
        .unwrap();
    let lt = e.frame(0.0, 5).unwrap();
    assert_eq!(
        lt.rows[0].bg[0].scroll_x, 6,
        "the program's own x should be exactly 6 (5 prior frames + this one), not 106"
    );
    assert_eq!(
        e.memory().oam[0].x,
        6,
        "the program's own obj[0].x should be exactly 6, not 102"
    );
}

/// (c) A controls frame-wide override composes with the program's OWN
/// authored `hdma`: within the hook's range the hook's own value for a
/// property controls didn't touch survives; outside it, the property that
/// was never overridden by anything shows the frame-wide default.
#[test]
fn frame_wide_override_composes_with_the_programs_own_hdma() {
    let main = "function frame(t, f)\n\
                  brightness = 9\n\
                  hdma(100, 150, function(y)\n\
                    bg[1].scroll.x = 7\n\
                    brightness = 3\n\
                  end)\n\
                end\n";
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("main.lua", main),
        ("controls.lua", &controls("  bg[1].scroll.x = 24\n")),
    ])
    .unwrap();
    let lt = e.frame(0.0, 0).unwrap();

    for y in [10usize, 120, 200] {
        assert_eq!(
            lt.rows[y].bg[0].scroll_x, 24,
            "row {y}: controls always wins bg1 scroll x"
        );
    }
    assert_eq!(
        lt.rows[120].brightness, 3,
        "inside main's own hdma range, its own write survives"
    );
    assert_eq!(
        lt.rows[10].brightness, 9,
        "outside it, the frame-wide default (controls didn't touch it)"
    );
}

/// (d) Memory precedence: a controls override on one field of a poke surface
/// (VRAM word, CGRAM entry, one OAM property) overlays only what it touches,
/// leaving the program's other pokes on the same surfaces untouched;
/// releasing restores exactly the program's own memory state.
#[test]
fn memory_precedence_overlays_only_what_controls_touches() {
    let main = "function frame(t, f)\n\
                  vram[0x1000] = 0x1111\n\
                  vram[0x1001] = 0x3333\n\
                  cgram[1] = 0x0001\n\
                  obj[0].tile = 7\n\
                end\n";
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("main.lua", main),
        (
            "controls.lua",
            &controls("  vram[0x1000] = 0x2222\n  cgram[1] = 0x7fff\n  obj[0].x = 96\n"),
        ),
    ])
    .unwrap();
    e.frame(0.0, 0).unwrap();
    assert_eq!(e.memory().vram[0x1000], 0x2222);
    assert_eq!(
        e.memory().vram[0x1001],
        0x3333,
        "untouched by controls, main's write survives"
    );
    assert_eq!(e.memory().cgram[1], 0x7fff);
    assert_eq!(
        e.memory().oam[0].tile,
        7,
        "untouched by controls, main's write survives"
    );
    assert_eq!(e.memory().oam[0].x, 96);

    e.set_sources(&[("main.lua", main), ("controls.lua", &controls(""))])
        .unwrap();
    e.frame(0.0, 1).unwrap();
    assert_eq!(e.memory().vram[0x1000], 0x1111);
    assert_eq!(e.memory().cgram[1], 0x0001);
    assert_eq!(e.memory().oam[0].x, 0);
}

/// (e) A controls-only `set_sources` never recompiles: the VM, its running
/// voice, the timer phase, and the program's own accumulators all keep
/// going. Contrast: an actual `main.lua` change forces a real recompile
/// (init reruns), proving the fast path really is what preserved state above.
#[test]
fn controls_only_reload_keeps_the_vm_hot_full_recompile_does_not() {
    let main = voice0_main();
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("main.lua", &main),
        ("controls.lua", &controls("  brightness = 3\n")),
    ])
    .unwrap();

    let mut lt4 = None;
    for f in 0..5u32 {
        lt4 = Some(e.frame(0.0, f).unwrap());
    }
    let lt4 = lt4.unwrap();
    assert!(
        has_sound(e.audio()),
        "voice 0 should still be sounding after 5 frames"
    );
    let ticks4 = lt4.rows[0].bg[2].scroll_x;

    e.set_sources(&[
        ("main.lua", &main),
        ("controls.lua", &controls("  brightness = 4\n")),
    ])
    .unwrap();
    let lt5 = e.frame(0.0, 5).unwrap();
    assert_eq!(lt5.rows[0].brightness, 4);
    assert_eq!(
        lt5.rows[0].bg[1].scroll_x, 6,
        "n should have continued from frame 4 (5), not reset to 1"
    );
    assert!(
        lt5.rows[0].bg[2].scroll_x > ticks4,
        "ticks should have continued, not reset"
    );
    assert!(has_sound(e.audio()), "voice 0 should still be sounding");

    // Contrast: a real main.lua change (trailing comment) forces a full
    // recompile — init() reruns, resetting n.
    let main_changed = format!("{main}-- trailing comment\n");
    e.set_sources(&[
        ("main.lua", &main_changed),
        ("controls.lua", &controls("  brightness = 4\n")),
    ])
    .unwrap();
    let lt6 = e.frame(0.0, 6).unwrap();
    assert_eq!(
        lt6.rows[0].bg[1].scroll_x, 1,
        "init should have rerun, resetting n"
    );
}

/// (f) A syntax error in a controls-only push is refused, attributed to
/// `controls.lua`, and leaves the previously-applying controls (and all
/// program state) exactly as they were; a subsequent valid push recovers.
#[test]
fn invalid_controls_keeps_the_previous_override_and_program_state() {
    let main = voice0_main();
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("main.lua", &main),
        ("controls.lua", &controls("  brightness = 4\n")),
    ])
    .unwrap();
    for f in 0..5u32 {
        e.frame(0.0, f).unwrap();
    }

    let broken =
        "markers = {\n}\n\nscanlines = {\n}\n\nfunction apply_pokes(\n  brightness = 9\nend\n";
    let err = e
        .set_sources(&[("main.lua", &main), ("controls.lua", broken)])
        .unwrap_err();
    assert_eq!(err.file.as_deref(), Some("controls.lua"));

    let lt = e.frame(0.0, 5).unwrap();
    assert_eq!(
        lt.rows[0].brightness, 4,
        "the last valid controls should still apply"
    );
    assert_eq!(
        lt.rows[0].bg[1].scroll_x, 6,
        "n should have kept counting through the failed push"
    );

    e.set_sources(&[
        ("main.lua", &main),
        ("controls.lua", &controls("  brightness = 6\n")),
    ])
    .unwrap();
    let lt = e.frame(0.0, 6).unwrap();
    assert_eq!(lt.rows[0].brightness, 6);
    assert_eq!(lt.rows[0].bg[1].scroll_x, 7, "n should still be continuous");
}

/// (g) Toy switch (a full recompile with both files different) drops the
/// old controls override outright; a program with no controls.lua at all
/// and a legacy `pokes.lua` + explicit `apply_pokes()` call keeps working
/// unchanged (see `scanline_pokes.rs`, untouched by this ticket).
#[test]
fn toy_switch_drops_old_controls_and_legacy_pokes_lua_still_works() {
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("main.lua", "function frame(t, f) end"),
        ("controls.lua", &controls("  brightness = 12\n")),
    ])
    .unwrap();
    assert_eq!(e.frame(0.0, 0).unwrap().rows[0].brightness, 12);

    e.set_sources(&[
        ("main.lua", "function frame(t, f) TM = 0x01 end"),
        ("controls.lua", &controls("  bg[1].scroll.x = 5\n")),
    ])
    .unwrap();
    let lt = e.frame(0.0, 0).unwrap();
    assert_eq!(
        lt.rows[0].brightness, 15,
        "the OLD controls override must be gone (power-on default)"
    );
    assert_eq!(
        lt.rows[0].bg[0].scroll_x, 5,
        "the NEW controls should apply"
    );

    let mut legacy = LuaEngine::new();
    legacy
        .set_sources(&[
            ("pokes.lua", "function apply_pokes() brightness = 2 end"),
            ("main.lua", "function frame(t, f) apply_pokes() end"),
        ])
        .unwrap();
    assert_eq!(legacy.frame(0.0, 0).unwrap().rows[0].brightness, 2);
}

/// (h) A runtime error inside `apply_pokes` surfaces through the same
/// `LuaError` shape as any other hook error, attributed to `controls.lua`,
/// and never touches the program's own globals — the next successful frame
/// continues the program's accumulator right where the errored one left it.
#[test]
fn runtime_error_inside_apply_pokes_is_attributed_and_program_state_stays_clean() {
    let main = "function frame(t, f) n = (n or 0) + 1; bg[2].scroll.x = n end";
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("main.lua", main),
        ("controls.lua", &controls("  nothing.x = 1\n")),
    ])
    .unwrap();
    let err = e.frame(0.0, 0).unwrap_err();
    assert_eq!(err.file.as_deref(), Some("controls.lua"));

    e.set_sources(&[
        ("main.lua", main),
        ("controls.lua", &controls("  brightness = 7\n")),
    ])
    .unwrap();
    let lt = e.frame(0.0, 1).unwrap();
    assert_eq!(lt.rows[0].brightness, 7);
    assert_eq!(
        lt.rows[0].bg[1].scroll_x, 2,
        "n should have continued across the errored frame (1 -> 2)"
    );
}

/// controls.lua runs before every user chunk regardless of its position in
/// the list: a `markers.<name>` reference pasted at a user file's top level
/// (the Timeline panel's copy chip) resolves, and `apply_pokes` is callable
/// from a top-level statement too.
#[test]
fn controls_chunk_runs_before_user_chunks_wherever_it_is_listed() {
    let doc =
        controls("  brightness = 3\n").replace("markers = {\n}", "markers = {\n  intro = 2.5,\n}");
    let main = "at = markers.intro\nfunction frame(t, f) bg[2].scroll.x = at * 2 end";
    let mut e = LuaEngine::new();
    e.set_sources(&[("main.lua", main), ("controls.lua", &doc)])
        .expect("markers must already exist when main.lua's top level runs");
    let lt = e.frame(0.0, 0).unwrap();
    assert_eq!(lt.rows[0].bg[1].scroll_x, 5);
    assert_eq!(lt.rows[0].brightness, 3);
}

/// (i) A program `hdma` hook missing its function argument (a typo'd
/// `hdma(0, 100)`) must not desync the splice index from the collected
/// hooks Vec — only FUNCTION-bearing `__ppu_hooks` entries are ever
/// collected, so `n_program` must count the same way or the splice index
/// can go out of range. Also proves splice ordering: the frame-wide
/// controls override beats the program's own hdma hook, and controls's own
/// band hook (registered by `apply_pokes` itself) beats the frame-wide
/// override in turn.
#[test]
fn program_hook_missing_its_function_argument_does_not_desync_the_splice_index() {
    let main = "function frame(t, f)\n\
                  brightness = 9\n\
                  hdma(0, 100)\n\
                  hdma(100, 150, function(y) bg[1].scroll.x = 7 end)\n\
                end\n";
    let doc = controls_with_scanlines(
        "  water = { first = 120, last = 223 },\n",
        "  bg[1].scroll.x = 24\n\
         hdma(scanlines.water.first, scanlines.water.last, function(y)\n\
           bg[1].scroll.x = 2\n\
         end)\n",
    );
    let mut e = LuaEngine::new();
    e.set_sources(&[("main.lua", main), ("controls.lua", &doc)])
        .unwrap();
    for f in 0..2u32 {
        let lt = e.frame(0.0, f).unwrap();
        assert_eq!(lt.rows[10].bg[0].scroll_x, 24, "frame {f}");
        assert_eq!(
            lt.rows[110].bg[0].scroll_x, 24,
            "frame {f}: frame-wide beats the program hook"
        );
        assert_eq!(
            lt.rows[125].bg[0].scroll_x, 2,
            "frame {f}: controls band beats frame-wide"
        );
        assert_eq!(lt.rows[110].brightness, 9, "frame {f}");
    }
}

/// (j) An explicit `apply_pokes()` call from inside the program's own
/// `frame()` runs under the same tracked env Phase A uses, so its writes
/// must be logged and undone by the same end-of-frame restore — not
/// discarded (old bug) or left to bake in permanently.
#[test]
fn explicit_apply_pokes_call_inside_program_frame_does_not_escape_the_undo_log() {
    let main = "function frame(t, f)\n\
                  x = (x or 0) + 1\n\
                  bg[1].scroll.x = x\n\
                  obj[0].x = obj[0].x + 1\n\
                  apply_pokes()\n\
                end\n";
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("main.lua", main),
        (
            "controls.lua",
            &controls("  bg[1].scroll.x = 100\n  obj[0].x = 96\n"),
        ),
    ])
    .unwrap();
    for f in 0..5u32 {
        let lt = e.frame(0.0, f).unwrap();
        assert_eq!(
            lt.rows[0].bg[0].scroll_x, 100,
            "frame {f}: override visible"
        );
        assert_eq!(e.memory().oam[0].x, 96, "frame {f}: override visible");
    }

    e.set_sources(&[("main.lua", main), ("controls.lua", &controls(""))])
        .unwrap();
    for f in 5..7u32 {
        e.frame(0.0, f).unwrap();
    }
    assert_eq!(
        e.memory().oam[0].x,
        7,
        "the explicit apply_pokes() call's writes must have been undone every frame, \
         so the program's own accumulator progressed by exactly 1/frame (7), not 98"
    );
}

/// (k) A fast-path controls push that fails at RUNTIME partway through
/// (after some top-level writes already landed on the real globals) must be
/// fully unwound: the previous good controls keep applying, and the
/// program can still read the previous good `markers` — not the failed
/// push's partial redefinition.
#[test]
fn fast_path_runtime_error_midway_through_controls_is_fully_undone() {
    let main = "function frame(t, f) bg[2].scroll.x = markers.intro * 2 end";
    let doc =
        controls("  brightness = 4\n").replace("markers = {\n}", "markers = {\n  intro = 2.5,\n}");
    let mut e = LuaEngine::new();
    e.set_sources(&[("main.lua", main), ("controls.lua", &doc)])
        .unwrap();
    let lt = e.frame(0.0, 0).unwrap();
    assert_eq!(lt.rows[0].brightness, 4);
    assert_eq!(lt.rows[0].bg[1].scroll_x, 5);

    let broken =
        "markers = {\n  intro = 9,\n}\n\nscanlines = {\n}\n\nlocal boom = nil\nboom.x = 1\n";
    let err = e
        .set_sources(&[("main.lua", main), ("controls.lua", broken)])
        .unwrap_err();
    assert_eq!(err.file.as_deref(), Some("controls.lua"));

    let lt = e.frame(0.0, 1).unwrap();
    assert_eq!(
        lt.rows[0].brightness, 4,
        "the last valid controls should still apply"
    );
    assert_eq!(
        lt.rows[0].bg[1].scroll_x, 5,
        "markers.intro must have been restored to 2.5, not left at the failed push's 9"
    );
}

/// (l) A fast-path controls push whose text no longer defines
/// `apply_pokes` must clear the previously-stashed function, not silently
/// keep re-applying the old chunk's override.
#[test]
fn fast_path_controls_push_without_apply_pokes_clears_the_stashed_override() {
    let main = "function frame(t, f) brightness = 5 end";
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("main.lua", main),
        ("controls.lua", &controls("  brightness = 12\n")),
    ])
    .unwrap();
    assert_eq!(e.frame(0.0, 0).unwrap().rows[0].brightness, 12);

    let no_apply_pokes = "markers = {\n}\n\nscanlines = {\n}\n";
    e.set_sources(&[("main.lua", main), ("controls.lua", no_apply_pokes)])
        .unwrap();
    assert_eq!(
        e.frame(0.0, 1).unwrap().rows[0].brightness,
        5,
        "no apply_pokes in the new text: the override must be gone"
    );
}

/// (m) A program that still calls `apply_pokes()` explicitly after a
/// fast-path push clears it gets a runtime error attributed to ITS OWN
/// file, not `controls.lua` — the global is genuinely nil, not silently
/// re-stashed from the previous chunk.
#[test]
fn explicit_apply_pokes_call_after_fast_path_clear_errors_on_the_callers_own_file() {
    let calls_it = "function frame(t, f) apply_pokes() end";
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("main.lua", calls_it),
        ("controls.lua", &controls("  brightness = 12\n")),
    ])
    .unwrap();
    let no_apply_pokes = "markers = {\n}\n\nscanlines = {\n}\n";
    e.set_sources(&[("main.lua", calls_it), ("controls.lua", no_apply_pokes)])
        .unwrap();
    let err = e.frame(0.0, 0).unwrap_err();
    assert_eq!(err.file.as_deref(), Some("main.lua"));
}

/// An error exit from the program's own `frame()` body — right after
/// an explicit `apply_pokes()` call it made — must restore the controls
/// undo log before returning, or that call's writes bake in permanently:
/// the next frame's `__ppu_controls_begin` discards the stale log without
/// ever undoing it.
#[test]
fn program_frame_error_after_explicit_apply_pokes_restores_the_undo_log() {
    let main = "function frame(t, f)\n\
                  obj[0].x = obj[0].x + 1\n\
                  apply_pokes()\n\
                  if f == 2 then error(\"boom\") end\n\
                end\n";
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("main.lua", main),
        ("controls.lua", &controls("  obj[0].x = 96\n")),
    ])
    .unwrap();

    for f in 0..=4u32 {
        let res = e.frame(0.0, f);
        if f == 2 {
            assert_eq!(res.unwrap_err().file.as_deref(), Some("main.lua"));
        } else {
            res.unwrap();
        }
    }

    e.set_sources(&[("main.lua", main), ("controls.lua", &controls(""))])
        .unwrap();
    for f in 5..=7u32 {
        e.frame(0.0, f).unwrap();
    }
    // Every frame 0..=4 ran its own `obj[0].x = obj[0].x + 1` exactly once,
    // including frame 2 (it errored only AFTER that increment) — 5
    // increments landed by the time controls is released at frame 5.
    // Frames 5,6,7 add 3 more: 5 + 3 = 8. Without the error-exit restore, frame 2's
    // explicit apply_pokes() write (96) is never undone (baked in instead
    // of restored to 3, its pre-error value), so the count instead lands at
    // 96 + 1 (frame 3) + 1 (frame 4) + 1 (frame 5) + 1 (frame 6) + 1 (frame
    // 7) = 101.
    assert_eq!(
        e.memory().oam[0].x,
        8,
        "the errored frame's explicit apply_pokes() write must have been undone"
    );
}

/// Same as above, but the explicit `apply_pokes()` call and the error
/// happen inside a `timer(...)` hook instead of `frame()`'s own body — the
/// other error exit after `__ppu_controls_begin` (through
/// `render_frame_audio`) must restore just as reliably.
#[test]
fn timer_hook_error_after_explicit_apply_pokes_restores_the_undo_log() {
    let main = "timer(0, 64, function()\n\
                  apply_pokes()\n\
                  if f_now == 2 then error(\"boom\") end\n\
                end)\n\
                function frame(t, f)\n\
                  f_now = f\n\
                  obj[0].x = obj[0].x + 1\n\
                end\n";
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("main.lua", main),
        ("controls.lua", &controls("  obj[0].x = 96\n")),
    ])
    .unwrap();

    for f in 0..=4u32 {
        let res = e.frame(0.0, f);
        if f == 2 {
            assert_eq!(res.unwrap_err().file.as_deref(), Some("main.lua"));
        } else {
            res.unwrap();
        }
    }

    e.set_sources(&[("main.lua", main), ("controls.lua", &controls(""))])
        .unwrap();
    for f in 5..=7u32 {
        e.frame(0.0, f).unwrap();
    }
    // Same arithmetic as the frame()-body variant above: 5 increments landed
    // by release (frame 2's increment ran before its timer hook errored),
    // plus 3 more after release = 8, not 101.
    assert_eq!(
        e.memory().oam[0].x,
        8,
        "the timer hook's explicit apply_pokes() write must have been undone"
    );
}

/// The end-of-frame restore must undo controls's writes BEFORE
/// re-baselining sticky globals to the frame-wide defaults, not after: a
/// controls BAND hook's first logged write for a key carries that row's
/// `write_state(row)` baseline as its "old" value, not the frame-wide
/// default, so restoring AFTER `write_state(&defaults)` clobbers the
/// program's own accumulator with a stray per-row value.
#[test]
fn controls_restore_runs_before_the_sticky_defaults_rebaseline() {
    let main = "function frame(t, f)\n\
                  bg[1].scroll.x = bg[1].scroll.x + 1\n\
                  bg[2].scroll.x = bg[1].scroll.x\n\
                  hdma(0, 10, function(y) bg[1].scroll.x = 0 end)\n\
                end\n";
    let doc = controls_with_scanlines(
        "  water = { first = 5, last = 8 },\n",
        "  hdma(scanlines.water.first, scanlines.water.last, function(y)\n\
           bg[1].scroll.x = 50\n\
         end)\n",
    );
    let mut e = LuaEngine::new();
    e.set_sources(&[("main.lua", main), ("controls.lua", &doc)])
        .unwrap();
    e.frame(0.0, 0).unwrap();
    let lt = e.frame(0.0, 1).unwrap();

    assert_eq!(
        lt.rows[0].bg[1].scroll_x, 2,
        "the program's own accumulator (mirrored into bg[2], which nothing \
         pokes) should have advanced 1 -> 2 across the two frames; with the \
         restore-after-rebaseline bug it reads 1"
    );
    assert_eq!(
        lt.rows[6].bg[0].scroll_x, 50,
        "inside the controls band, the band hook still wins"
    );
    assert_eq!(
        lt.rows[0].bg[0].scroll_x, 0,
        "outside the band but inside the program's own hdma, its hook still wins"
    );

    // Baseline sanity: the same program with no controls.lua at all must
    // reach the same accumulator value, proving the 2 above is the program's
    // own arithmetic and not an artifact of controls.
    let mut plain = LuaEngine::new();
    plain.set_sources(&[("main.lua", main)]).unwrap();
    plain.frame(0.0, 0).unwrap();
    let lt = plain.frame(0.0, 1).unwrap();
    assert_eq!(lt.rows[0].bg[1].scroll_x, 2);
}
