//! The generated-`pokes.lua` contract for the SCANLINE poke dialect.
//!
//! The web inspector generates this file (`web/src/studio/pokes/pokes.ts`
//! `pokesToLua`, keyframes from `scanlinePokes.ts`); the engine has to run it.
//! These tests pin the exact generated shape so a change to either side that
//! breaks the other fails here rather than silently producing a flat window.
//!
//! The Lua below is verbatim `pokesToLua` output — keep it byte-identical to
//! what the generator emits (`pokes.test.ts` pins the same text on the TS side).

use ppu_core::{LuaEngine, WIN_SCANLINE_STRIDE};

/// Verbatim generated preamble + hook for two keyframed window edges.
const GENERATED: &str = r#"-- pokes.lua · generated by the inspector — read-only.
-- Poke register/CGRAM values in the inspector to fill this in. To save a
-- configuration, copy apply_pokes() into your own file under a new name.
-- Hand-edits here are overwritten by the next poke.
-- Per-scanline pokes: keyframes {{y,value},…} interpolated down the frame,
-- holding the end values outside the keyframed range.
local function pk(kf, y)
  local n = #kf
  if y <= kf[1][1] then return kf[1][2] end
  for i = 2, n do
    local a, b = kf[i - 1], kf[i]
    if y <= b[1] then
      local d = b[1] - a[1]
      if d <= 0 then return b[2] end
      return a[2] + (b[2] - a[2]) * (y - a[1]) / d
    end
  end
  return kf[n][2]
end
local function pki(kf, y) return floor(pk(kf, y) + 0.5) end
local function pkf(kf, y) return pk(kf, y) end
function apply_pokes()
  TM = 0x13
  hdma(0, 223, function(y)
    win.w1.hi = pki({{0,128},{112,198},{223,128}}, y) -- $2127 · per-scanline
    win.w1.lo = pki({{0,128},{112,58},{223,128}}, y) -- $2126 · per-scanline
  end)
end
"#;

const MAIN: &str = r#"function frame(t, f)
  apply_pokes()
  mode = 1; brightness = 15
end
"#;

fn run(pokes: &str, main: &str) -> Vec<u8> {
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("pokes.lua".into(), pokes.into()),
        ("main.lua".into(), main.into()),
    ])
    .expect("generated pokes.lua must compile");
    let lt = e.frame(0.0, 0).expect("frame must not raise");
    ppu_core::window_scanline_bytes(&lt)
}

fn edges(bytes: &[u8], y: usize) -> (u8, u8) {
    (
        bytes[y * WIN_SCANLINE_STRIDE],
        bytes[y * WIN_SCANLINE_STRIDE + 1],
    )
}

#[test]
fn generated_scanline_pokes_interpolate_between_keyframes() {
    let b = run(GENERATED, MAIN);
    // On a keyframe: exactly the keyframed value.
    assert_eq!(edges(&b, 0), (128, 128), "first keyframe");
    assert_eq!(edges(&b, 112), (58, 198), "middle keyframe");
    assert_eq!(edges(&b, 223), (128, 128), "last keyframe");
    // Halfway between lines 0 and 112: lo = 128 + (58-128)/2 = 93.
    assert_eq!(edges(&b, 56), (93, 163), "linear midpoint");
    // Monotone on the way in — the curve really is swept, not stepped.
    assert!(edges(&b, 30).0 > edges(&b, 60).0);
}

#[test]
fn generated_hook_rounds_rather_than_dropping_fractional_values() {
    // The DSL ignores a fractional write to an integer register (to_integer()
    // rejects it), so pki must round. Line 1 of a 0..112 ramp from 128 to 58
    // interpolates to 127.375 — without rounding the edge would silently stay
    // at its default 0.
    let b = run(GENERATED, MAIN);
    assert_eq!(edges(&b, 1).0, 127, "fractional interpolation must round");
    assert_ne!(edges(&b, 1).0, 0, "a dropped write would leave the default");
}

#[test]
fn frame_wide_pokes_still_apply_alongside_the_hook() {
    let mut e = LuaEngine::new();
    e.set_sources(&[
        ("pokes.lua".into(), GENERATED.into()),
        ("main.lua".into(), MAIN.into()),
    ])
    .unwrap();
    let lt = e.frame(0.0, 0).unwrap();
    // TM = 0x13 is a plain assignment in the same apply_pokes().
    assert_eq!(lt.rows[0].tm, 0x13);
}

#[test]
fn a_script_hdma_still_wins_over_a_scanline_poke() {
    // apply_pokes() registers its hook first, so a hook the script registers
    // later is applied after it — the documented "script wins" convention
    // survives for hook-vs-hook.
    let main = r#"function frame(t, f)
  apply_pokes()
  mode = 1
  hdma(0, 223, function(y) win.w1.lo = 7 end)
end
"#;
    let b = run(GENERATED, main);
    assert_eq!(edges(&b, 112).0, 7, "the script's later hook must win");
    assert_eq!(edges(&b, 112).1, 198, "an untouched edge keeps the poke");
}

/// Verbatim generated output for two pokes on DIFFERENT ranges: one hook per
/// range, each doing its own thing. This is the shape the keyframe track's
/// per-poke range control produces.
const GENERATED_RANGES: &str = r#"-- pokes.lua · generated by the inspector — read-only.
-- Per-scanline pokes: keyframes {{y,value},…} interpolated down the frame,
-- holding the end values outside the keyframed range.
local function pk(kf, y)
  local n = #kf
  if y <= kf[1][1] then return kf[1][2] end
  for i = 2, n do
    local a, b = kf[i - 1], kf[i]
    if y <= b[1] then
      local d = b[1] - a[1]
      if d <= 0 then return b[2] end
      return a[2] + (b[2] - a[2]) * (y - a[1]) / d
    end
  end
  return kf[n][2]
end
local function pki(kf, y) return floor(pk(kf, y) + 0.5) end
local function pkf(kf, y) return pk(kf, y) end
function apply_pokes()
  hdma(0, 95, function(y)
    win.w1.hi = pki({{0,10},{95,60}}, y) -- $2127 · per-scanline
  end)
  hdma(96, 223, function(y)
    win.w1.lo = pki({{96,20},{223,120}}, y) -- $2126 · per-scanline
  end)
end
"#;

#[test]
fn scoped_hooks_each_own_only_their_own_band() {
    let b = run(GENERATED_RANGES, MAIN);
    // Top band: only w1.hi is driven; w1.lo keeps the frame default.
    assert_eq!(edges(&b, 0), (0, 10));
    assert_eq!(edges(&b, 95), (0, 60));
    // Bottom band: only w1.lo is driven; w1.hi falls back to the default.
    assert_eq!(edges(&b, 96), (20, 0));
    assert_eq!(edges(&b, 223), (120, 0));
}

#[test]
fn outside_its_range_a_scanline_poke_leaves_the_script_in_charge() {
    // The point of scoping: the hook does not run there, so a plain frame-wide
    // assignment in the script stands on those lines.
    let main = r#"function frame(t, f)
  apply_pokes()
  mode = 1
  win.w1.lo = 7
end
"#;
    let b = run(GENERATED_RANGES, main);
    assert_eq!(edges(&b, 0).0, 7, "above the band, the script wins");
    assert_eq!(edges(&b, 95).0, 7, "still above the band");
    assert_eq!(edges(&b, 96).0, 20, "inside the band, the poke wins");
}

#[test]
fn a_scanline_poke_beats_a_frame_wide_script_assignment() {
    // The inherent asymmetry the UI warns about: a hook always overrides the
    // frame defaults, so unlike a frame-wide poke, a plain later assignment in
    // the script does NOT win. Pinned so the behaviour cannot drift silently
    // away from what the panel promises.
    let main = r#"function frame(t, f)
  apply_pokes()
  mode = 1
  win.w1.lo = 7
end
"#;
    let b = run(GENERATED, main);
    assert_eq!(edges(&b, 112).0, 58, "the hook overrides the frame default");
}
