//! Shared helpers for the tutorial-toy golden tests (tutorial_*.rs).
//! Mirrors the private helpers in golden_demos.rs — that file predates this
//! module and deliberately keeps its own copies (PPU-96 owns the unification).
#![allow(dead_code)]
use ppu_core::{convert_source, ConvertOptions, LuaEngine, SourceKind, HEIGHT, WIDTH};

/// Empty pokes.lua chunk — mirrors `pokesToLua([])` / `EMPTY_POKES` from
/// web/src/studio/pokes/pokes.ts byte-for-byte.
pub const EMPTY_POKES_SRC: &str = r#"-- pokes.lua · generated by the inspector — read-only.
-- Poke register/CGRAM values in the inspector to fill this in. To save a
-- configuration, copy apply_pokes() into your own file under a new name.
-- Hand-edits here are overwritten by the next poke.
function apply_pokes()
end
"#;

/// Convert an RGBA generator through the format-committed source path and
/// register it under `name` (mirrors the web `convertSource` + `addSource`
/// flow). The committed format MUST match the mode's bind depth for the demo
/// that uses it, or the strict bind validation renders the layer blank.
pub fn add_bg(e: &mut LuaEngine, name: &str, rgba: Vec<u8>, w: u32, h: u32, bit_depth: u8) {
    let opts = ConvertOptions {
        bit_depth: Some(bit_depth),
        ..Default::default()
    };
    let (payload, _) = convert_source(SourceKind::Bg, &opts, &rgba, w, h).unwrap();
    e.add_source(name, &payload.encode()).unwrap();
}

pub fn add_m7(e: &mut LuaEngine, name: &str, rgba: Vec<u8>, w: u32, h: u32) {
    let (payload, _) =
        convert_source(SourceKind::M7, &ConvertOptions::default(), &rgba, w, h).unwrap();
    e.add_source(name, &payload.encode()).unwrap();
}

pub fn add_obj(e: &mut LuaEngine, name: &str, rgba: Vec<u8>, w: u32, h: u32) {
    let opts = ConvertOptions {
        cell_size: Some(8),
        ..Default::default()
    };
    let (payload, _) = convert_source(SourceKind::Obj, &opts, &rgba, w, h).unwrap();
    e.add_source(name, &payload.encode()).unwrap();
}

pub fn add_sheet(e: &mut LuaEngine, name: &str, rgba: Vec<u8>, w: u32, h: u32, bit_depth: u8) {
    let opts = ConvertOptions {
        bit_depth: Some(bit_depth),
        ..Default::default()
    };
    let (payload, _) = convert_source(SourceKind::Sheet, &opts, &rgba, w, h).unwrap();
    e.add_source(name, &payload.encode()).unwrap();
}

/// Build an engine over `files` (name, source) with pokes.lua prepended,
/// mirroring web tab order. Register sources on the engine BEFORE this if the
/// closure needs them — or use `engine_with(assets, files)` below.
pub fn engine_with(assets: &mut dyn FnMut(&mut LuaEngine), files: &[(&str, &str)]) -> LuaEngine {
    let mut e = LuaEngine::new();
    assets(&mut e);
    let mut chunks = Vec::with_capacity(files.len() + 1);
    chunks.push(("pokes.lua", EMPTY_POKES_SRC));
    chunks.extend_from_slice(files);
    e.set_sources(&chunks).unwrap();
    e
}

/// One RGBA pixel at (x, y) in a WIDTH*HEIGHT framebuffer.
pub fn px(fb: &[u8], x: usize, y: usize) -> &[u8] {
    &fb[(y * WIDTH + x) * 4..][..4]
}

pub fn decode_png(path: &str) -> Vec<u8> {
    let decoder = png::Decoder::new(std::fs::File::open(path).unwrap());
    let mut reader = decoder.read_info().unwrap();
    let mut buf = vec![0u8; reader.output_buffer_size()];
    let info = reader.next_frame(&mut buf).unwrap();
    buf.truncate(info.buffer_size());
    buf
}

pub fn write_png(path: &str, fb: &[u8]) {
    std::fs::create_dir_all("tests/fixtures").unwrap();
    let file = std::fs::File::create(path).unwrap();
    let mut encoder = png::Encoder::new(file, WIDTH as u32, HEIGHT as u32);
    encoder.set_color(png::ColorType::Rgba);
    encoder.set_depth(png::BitDepth::Eight);
    encoder
        .write_header()
        .unwrap()
        .write_image_data(fb)
        .unwrap();
}
